[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$existingJsonRaw = Get-Content -Raw -Encoding UTF8 './data/vocabulary.json'
$existing = $existingJsonRaw | ConvertFrom-Json
Write-Host "Current total existing words in database: $($existing.Length)"

$existingKanjiSet = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
foreach ($item in $existing) {
    if ($item.kanji) {
        $existingKanjiSet.Add($item.kanji.Trim()) | Out-Null
    }
}

$candidatePool4 = @(
    # Literature, Arts & Idioms
    @{kanji="随筆"; furigana="ずいひつ"; arti="esai reflektif catatan perenungan sastra"},
    @{kanji="戯曲"; furigana="ぎきょく"; arti="naskah drama lakon sandiwara teater"},
    @{kanji="随想"; furigana="ずいそう"; arti="sketsa renungan kontemplasi lepas pengarang"},
    @{kanji="詩篇"; furigana="しへん"; arti="bait syair gubahan puisi kidung pujian"},
    @{kanji="短歌"; furigana="たんか"; arti="puisi klasik jepang pola 31 suku kata"},
    @{kanji="俳句"; furigana="はいく"; arti="puisi bait pendek jepang pola 17 suku kata"},
    @{kanji="季語"; furigana="きご"; arti="kosakata penanda pergantian musim puisi haiku"},
    @{kanji="韻律"; furigana="いんりつ"; arti="rima irama metrum musikalitas kidung sajak"},
    @{kanji="散文"; furigana="さんぶん"; arti="karangan prosa bebas narasi mengalir"},
    @{kanji="韻文"; furigana="いんぶん"; arti="karangan terikat sajak bait berima puitis"},
    @{kanji="叙情"; furigana="じょじょう"; arti="curahan penghayatan liris perasaan batin"},
    @{kanji="叙事"; furigana="じょじ"; arti="narasi kronik epos hikayat sejarah epik"},
    @{kanji="描写"; furigana="びょうしゃ"; arti="deskripsi pelukisan rinci suasana watak"},
    @{kanji="比喩"; furigana="ひゆ"; arti="bahasa kiasan metafora perumpamaan analogi"},
    @{kanji="暗示"; furigana="あんじ"; arti="petunjuk tersirat isyarat sugesti implisit"},
    @{kanji="示唆"; furigana="しさ"; arti="indikasi petunjuk tersirat saran rekomendasi"},
    @{kanji="婉曲"; furigana="えんきょく"; arti="eufemisme pengungkapan halus secara santun"},
    @{kanji="風刺"; furigana="ふうし"; arti="satir parodi kritik jenaka terhadap tatanan"},
    @{kanji="皮肉"; furigana="ひにく"; arti="ironi sindiran getir sarkasme kenyataan"},
    @{kanji="機知"; furigana="きち"; arti="kecerdasan akal tanggap jenaka spontan"},
    @{kanji="機転"; furigana="きてん"; arti="kelincahan taktis improvisasi cerdik akal"},
    @{kanji="自由奔放"; furigana="じゆうほんぽう"; arti="berjiwa bebas liar tanpa kekangan norma kaku"},
    @{kanji="縦横無尽"; furigana="じゅうおうむじん"; arti="leluasa bergerak lincah ke segenap penjuru"},
    @{kanji="天衣無縫"; furigana="てんいむほう"; arti="sempurna alami murni tanpa kepura-puraan"},
    @{kanji="純真無垢"; furigana="じゅんしんむく"; arti="suci murni tanpa noda keburukan nurani"},
    @{kanji="一刀両断"; furigana="いっとうりょうだん"; arti="pengambilan keputusan tegas tanpa ragu memotong"},
    @{kanji="乾坤一擲"; furigana="けんこんいってき"; arti="pertaruhan besar mempertaruhkan segalanya nasib"},
    @{kanji="千載一遇"; furigana="せんざいいちぐう"; arti="kesempatan langka emas sekali seumur masa"},
    @{kanji="一網打尽"; furigana="いちもうだじん"; arti="penangkapan serempak meringkus kawanan sindikat"},
    @{kanji="臥薪嘗胆"; furigana="がしんしょうたん"; arti="perjuangan keras menahan derita demi pembalasan"},
    @{kanji="捲土重来"; furigana="けんどちょうらい"; arti="bangkit kembali menggebrak pasca keterpurukan"},
    @{kanji="質実剛健"; furigana="しつじつごうけん"; arti="bersahaja sederhana berjiwa kokoh ksatria"},
    @{kanji="容姿端麗"; furigana="ようしたんれい"; arti="berparas elok anggun rupawan memikat kalbu"},
    @{kanji="才色兼備"; furigana="さいしょくけんび"; arti="cerdas berwawasan sekaligus berparas jelita"},
    @{kanji="誠心誠意"; furigana="せいしんせいい"; arti="sepenuh jiwa raga tulus ikhlas berbakti"},
    @{kanji="百発百中"; furigana="ひゃっぱつひゃくちゅう"; arti="tembakan jitu tepat sasaran tanpa pernah meleset"},
    @{kanji="日常茶飯事"; furigana="にちじょうさはんじ"; arti="hal lumrah sepele lazim dijumpai setiap hari"},

    # Etiquette, Society, Ceremonies & Human Affairs
    @{kanji="作法"; furigana="さほう"; arti="tata krama kaidah tata krama etiket perjamuan"},
    @{kanji="儀礼"; furigana="ぎれい"; arti="protokoler formalitas tata susila kesopanan"},
    @{kanji="儀式"; furigana="ぎしき"; arti="prosesi upacara ritual khidmat perayaan adat"},
    @{kanji="典礼"; furigana="てんれい"; arti="tata urutan peribadatan liturgi suci resmi"},
    @{kanji="冠婚葬祭"; furigana="かんこんそうさい"; arti="empat daur seremoni adat tradisi keluarga"},
    @{kanji="披露宴"; furigana="ひろうえん"; arti="resepsi perayaan jamuan resepsi pernikahan"},
    @{kanji="祝宴"; furigana="しゅくえん"; arti="pesta jamuan perayaan suka cita kegemilangan"},
    @{kanji="献杯"; furigana="けんぱい"; arti="sulangan hening penghormatan arwah mendiang"},
    @{kanji="香典"; furigana="こうでん"; arti="uang sumbangan duka cita bela sungkawa ziarah"},
    @{kanji="弔慰"; furigana="ちょうい"; arti="ungkapan duka cita simpati atas wafatnya kerabat"},
    @{kanji="弔電"; furigana="ちょうでん"; arti="kawat telegram bela sungkawa duka cita resmi"},
    @{kanji="祝電"; furigana="しゅくでん"; arti="telegram kawat ucapan selamat atas pelantikan"},
    @{kanji="祝辞"; furigana="しゅくじ"; arti="pidato amanat ucapan selamat resepsi pelantikan"},
    @{kanji="弔辞"; furigana="ちょうじ"; arti="elegi pidato belasungkawa penghormatan jenazah"},
    @{kanji="追悼"; furigana="ついとう"; arti="upacara mengenang jasa kebajikan sang perintis"},
    @{kanji="慰霊"; furigana="いれい"; arti="persemayaman doa mendoakan ketenteraman arwah"},
    @{kanji="参拝"; furigana="さんぱい"; arti="kunjungan ziarah memanjatkan doa di kuil agung"},
    @{kanji="巡礼"; furigana="じゅんれい"; arti="perjalanan ziarah safar religi ke tapak suci"},
    @{kanji="寄付"; furigana="きふ"; arti="donasi sumbangan amal sukarela kemanusiaan"},
    @{kanji="寄贈"; furigana="きぞう"; arti="penghibahan wakaf sumbangan koleksi pustaka"},
    @{kanji="贈呈"; furigana="ぞうてい"; arti="penyerahan bingkisan tanda mata plakat kenangan"},
    @{kanji="進呈"; furigana="しんてい"; arti="pemberian cuma-cuma hadiah souvenir apresiasi"},
    @{kanji="寄与"; furigana="きよ"; arti="sumbangsih andil kontribusi kemajuan peradaban"},
    @{kanji="功績"; furigana="こうせき"; arti="rekam jejak jasa bakti gemilang bagi persada"},
    @{kanji="勲功"; furigana="くんこう"; arti="jasa kepahlawanan patriotik pengorbanan jiwa"},
    @{kanji="叙勲"; furigana="じょくん"; arti="penganugerahan bintang lencana tanda kehormatan"},
    @{kanji="表彰"; furigana="ひょうしょう"; arti="pemberian piagam penghargaan resmi prestasi karya"},
    @{kanji="授与"; furigana="じゅよ"; arti="penganugerahan penyerahan trofi piala mahkota"},
    @{kanji="授権"; furigana="じゅけん"; arti="pelimpahan hak pemberian kuasa mandat otoritas"},
    @{kanji="委任"; furigana="いにん"; arti="pendelegasian wewenang surat kuasa resmi wali"},
    @{kanji="委嘱"; furigana="いしょく"; arti="penunjukan pengangkatan tenaga konsultan pakar"},
    @{kanji="嘱託"; furigana="しょくたく"; arti="pengangkatan pegawai kontrak tugas penasihat"},
    @{kanji="臨時"; furigana="りんじ"; arti="bersifat darurat insidental ad-hoc temporer"},
    @{kanji="常時"; furigana="じょうじ"; arti="senantiasa standby setiap waktu terus menyala"},
    @{kanji="随時"; furigana="ずいじ"; arti="kapan saja sewaktu-waktu terbuka fleksibel"},
    @{kanji="即時"; furigana="そくじ"; arti="seketika itu juga tanpa jeda penundaan kilat"},
    @{kanji="定刻"; furigana="ていこく"; arti="waktu yang telah dijadwalkan tepat pada jamnya"},
    @{kanji="定着"; furigana="ていちゃく"; arti="membudaya mengakar mapan dalam tatanan warga"},
    @{kanji="浸透"; furigana="しんとう"; arti="meresap menembus kesadaran paradigma khalayak"},
    @{kanji="伝播"; furigana="でんぱ"; arti="penyebarluasan transmisi getaran gelombang berita"},
    @{kanji="蔓延"; furigana="まんえん"; arti="penyebaran perebakan masif virus di kota besar"},
    @{kanji="横行"; furigana="おうこう"; arti="maraknya merajalela aksi pungutan liar jalanan"},
    @{kanji="暗躍"; furigana="あんやく"; arti="bergerak lincah bergerilya di balik tirai kekuasaan"},
    @{kanji="奮闘"; furigana="ふんとう"; arti="perjuangan gigih berpeluh keringat menembus asa"},
    @{kanji="健闘"; furigana="けんとう"; arti="perjuangan gigih bertarung pantang menyerah"},
    @{kanji="奮起"; furigana="ふんき"; arti="bangkit mengumpulkan tekad bangkit dari rebah"},
    @{kanji="鼓舞"; furigana="こぶ"; arti="mengobarkan memompa moril keberanian laskar"},
    @{kanji="激励"; furigana="げきれい"; arti="penyemangatan memompa suntikan motivasi juang"},
    @{kanji="催促"; furigana="さいそく"; arti="desakan penagihan pelunasan tugas tenggat"},
    @{kanji="督促"; furigana="とくそく"; arti="surat peringatan somasi tunggakan cicilan"},
    @{kanji="戒告"; furigana="かいこく"; arti="teguran tertulis pembinaan etika kedinasan"},
    @{kanji="訓告"; furigana="くんこく"; arti="peringatan lisan pembinaan kedisiplinan kerja"},
    @{kanji="懲戒"; furigana="ちょうかい"; arti="hukuman sanksi indisipliner pemecatan oknum"},
    @{kanji="停職"; furigana="ていしょく"; arti="skorsing pembebasan tugas dinas sementara"},
    @{kanji="減給"; furigana="げんきゅう"; arti="pemotongan pemangkasan gaji akibat kelalaian"},
    @{kanji="勧告"; furigana="かんこく"; arti="rekomendasi anjuran perbaikan tata kelola"},
    @{kanji="諮問"; furigana="しもん"; arti="permohonan telaah nasehat kepada dewan pakar"},
    @{kanji="答申"; furigana="とうしん"; arti="laporan kajian rekomendasi resmi balasan komisi"},
    @{kanji="提言"; furigana="ていげん"; arti="pengajuan formula rekomendasi solusi strategis"},
    @{kanji="請願"; furigana="せいがん"; arti="petisi resmi warga menuntut keadilan peradilan"},
    @{kanji="嘆願"; furigana="たんがん"; arti="permohonan memelas pengampunan hukuman grasi"},
    @{kanji="陳情"; furigana="ちんじょう"; arti="penyampaian keluhan aspirasi rakyat jelata"},

    # Logic, Philosophy & Abstract Thought
    @{kanji="本質"; furigana="ほんしつ"; arti="esensi hakikat terdalam substansi kebenaran"},
    @{kanji="実質"; furigana="じっしつ"; arti="substansi bobot materiil kenyataan riil"},
    @{kanji="形式的"; furigana="けいしきてき"; arti="bersifat seremonial basa-basi formalitas raga"},
    @{kanji="内面"; furigana="ないめん"; arti="kedalaman relung batin sukma kepribadian"},
    @{kanji="多面的"; furigana="ためんてき"; arti="multidimensional komprehensif dari aneka sisi"},
    @{kanji="一面的"; furigana="いちめんてき"; arti="sepihak picik dangkal tinjauan kacamata pandang"},
    @{kanji="全面的"; furigana="ぜんめんてき"; arti="secara menyeluruh totalitas segenap sektor"},
    @{kanji="局所的"; furigana="きょくしょてき"; arti="bersifat lokal terfokus spasial area sempit"},
    @{kanji="普遍"; furigana="ふへん"; arti="keuniversalan berlaku umum di seantero jagat"},
    @{kanji="普遍的"; furigana="ふへんてき"; arti="bersifat universal abadi melintasi tapak zaman"},
    @{kanji="特殊性"; furigana="とくしゅせい"; arti="keunikan partikularitas sifat kekhasan lokal"},
    @{kanji="一般性"; furigana="いっぱんせい"; arti="generalitas keabsahan umum yang lazim berlaku"},
    @{kanji="必然"; furigana="ひつぜん"; arti="keniscayaan kemutlakan konsekuensi alamiah"},
    @{kanji="必然的"; furigana="ひつぜんてき"; arti="secara niscaya pasti terjadi tiada tercegah"},
    @{kanji="偶然性"; furigana="ぐうぜんせい"; arti="kebetulan anomali probabilitas tak terduga"},
    @{kanji="蓋然性"; furigana="がいぜんせい"; arti="derajat probabilitas peluang kebenaran dugaan"},
    @{kanji="整合性"; furigana="せいごうせい"; arti="konsistensi keselarasan logika nalar utuh"},
    @{kanji="矛盾"; furigana="むじゅん"; arti="kontradiksi pertentangan logika tolak belakang"},
    @{kanji="逆説"; furigana="ぎゃくせつ"; arti="paradoks ungkapan kontradiktif sarat filsafat"},
    @{kanji="詭弁"; furigana="きべん"; arti="sofisme silat lidah logika keliru memelintir"},
    @{kanji="屁理屈"; furigana="へりくつ"; arti="dalih dicari-cari alasan mengada-ada membantah"},
    @{kanji="こじつけ"; furigana="こじつけ"; arti="mencocok-cocokkan tafsiran secara dipaksakan"},
    @{kanji="誇張"; furigana="こちょう"; arti="hiperbola membesar-besarkan fakta kenyataan"},
    @{kanji="歪曲"; furigana="わいきょく"; arti="distorsi pemutarbalikan fakta kebenaran cerita"},
    @{kanji="誇示する"; furigana="こじする"; arti="memamerkan unjuk superioritas kekuatan armada"},
    @{kanji="披瀝"; furigana="ひれき"; arti="pengungkapan pencurahan isi dada nurani tulus"},
    @{kanji="吐露"; furigana="とろ"; arti="pencurahan pengakuan blak-blakan rahasia kalbu"},
    @{kanji="独白"; furigana="どくはく"; arti="monolog berbicara sendirian mencurahkan isi rasa"},
    @{kanji="沈黙"; furigana="ちんもく"; arti="keheningan membisu diam seribu bahasa seroja"},
    @{kanji="静寂"; furigana="せいじゃく"; arti="kesunyian kedamaian hening sunyi senyap rimba"},
    @{kanji="静謐"; furigana="せいひつ"; arti="ketenteraman teduh damai hening jauh dari bising"},
    @{kanji="喧騒"; furigana="けんそう"; arti="hiruk-pikuk keriuhan gemuruh kota megapolitan"},
    @{kanji="騒然"; furigana="そうぜん"; arti="kegemparan kegaduhan suasana histeris massa"},
    @{kanji="混沌"; furigana="こんとん"; arti="kekacauan ketiadaan tatanan kosmik khaos gulita"},
    @{kanji="調和"; furigana="ちょうわ"; arti="keharmonisan keselarasan nada rona paduan cita"},
    @{kanji="不協和音"; furigana="ふきょうわおん"; arti="nada sumbang disonansi keretakan kongsi kawan"},

    # Dynamic Verbs & Mental Actions
    @{kanji="持ち越す"; furigana="もちこす"; arti="menunda membawa draf sisa agenda ke esok hari"},
    @{kanji="据え置く"; furigana="すえおく"; arti="mempertahankan membiarkan tarif konstan stabil"},
    @{kanji="差し止める"; furigana="さしとめる"; arti="mencekal menangguhkan penyiaran surat kabar"},
    @{kanji="引き締める"; furigana="ひきしめる"; arti="mengencangkan ikat pinggang pengetatan kas"},
    @{kanji="張り詰める"; furigana="はりつめる"; arti="suasana tegang mencekam konsentrasi tinggi"},
    @{kanji="突き止める"; furigana="つきとめる"; arti="mengusut menyingkap tuntas akar sebab perkara"},
    @{kanji="突き詰める"; furigana="つきつめる"; arti="menelaah mengkaji sampai ke hakikat terdalam"},
    @{kanji="追い詰める"; furigana="おいつめる"; arti="memojokkan mengepung buronan ke jalan buntu"},
    @{kanji="追い立てる"; furigana="おいたてる"; arti="menggiring memacu laju ternak terburu-buru"},
    @{kanji="掻き立てる"; furigana="かきたてる"; arti="menyulut membakar luapan hasrat rasa penasaran"},
    @{kanji="引き立てる"; furigana="ひきたてる"; arti="menonjolkan mempercantik rupa; mendukung kawan"},
    @{kanji="打ち立てる"; furigana="うちたてる"; arti="menorehkan memancangkan tonggak sejarah baru"},
    @{kanji="取り仕切る"; furigana="とりしきる"; arti="mengomandoi memimpin jalannya kendali acara"},
    @{kanji="切り替える"; furigana="きりかえる"; arti="mengalihkan memutar haluan pola pikir fokus"},
    @{kanji="踏み切る"; furigana="ふみきる"; arti="memantapkan langkah mengambil keputusan berani"},
    @{kanji="割り切る"; furigana="わりきる"; arti="berpikir rasional membedakan emosi dan urusan"},
    @{kanji="買い込む"; furigana="かいこむ"; arti="memborong menimbun pasokan sembako di rumah"},
    @{kanji="抱え込む"; furigana="かかえこむ"; arti="memikul sendiri memendam beban kepedihan raga"},
    @{kanji="呑み込む"; furigana="のみこむ"; arti="menelan pahit realita; memahami seluk-beluk"},
    @{kanji="染み込む"; furigana="しみこむ"; arti="merembes meresap ke pori kain; mengakar jiwa"},
    @{kanji="打ち解ける"; furigana="うちとける"; arti="mencairkan kebekuan membuka hati bercengkerama"},
    @{kanji="解きほぐす"; furigana="ときほぐす"; arti="mengurai benang kusut meredakan tegang saraf"},
    @{kanji="もつれる"; furigana="もつれる"; arti="kusut membelit; kaku lidah kelu bicara"},
    @{kanji="こじれる"; furigana="こじれる"; arti="menjadi semakin rumit runyam sengketa kusut"},
    @{kanji="途絶える"; furigana="とだえる"; arti="terputus padam kontak sinyal tiada kabar berita"},
    @{kanji="途切れる"; furigana="とぎれる"; arti="terhenti sejenak jeda jeda sejenak pembicaraan"},
    @{kanji="立ち消える"; furigana="たちぎえる"; arti="padam lenyap menguap begitu saja rencana ide"},
    @{kanji="見劣りする"; furigana="みおとりする"; arti="tampak kalah mutunya jika disandingkan saingan"},
    @{kanji="見違える"; furigana="みちがえる"; arti="berubah pangling memesona tiada mengenali"},
    @{kanji="見とれる"; furigana="みとれる"; arti="terpesona terpukau terhipnotis elok parasnya"},
    @{kanji="持ちこたえる"; furigana="もちこたえる"; arti="bertahan tabah menahan cobaan badai nestapa"},
    @{kanji="持ち上げる"; furigana="もちあげる"; arti="mengangkat memuji menyanjung melambungkan hati"},
    @{kanji="煽てる"; furigana="おだてる"; arti="menyanjung merayu gombal mencari pamrih muka"},
    @{kanji="欺く"; furigana="あざむく"; arti="memperdaya menipu musuh dengan siasat kancil"},
    @{kanji="謀る"; furigana="はかる"; arti="merencanakan konspirasi jahat menggulingkan tahta"},
    @{kanji="唆す"; furigana="そそのかす"; arti="menghasut membisikkan bujuk rayu berbuat nista"},
    @{kanji="煽る"; furigana="あおる"; arti="mengipas-ngipasi menyulut bara api kemarahan"},
    @{kanji="脅かす"; furigana="おびやかす"; arti="merongrong mengancam kedaulatan kedamaian nusa"},
    @{kanji="脅す"; furigana="おどす"; arti="menggertak menakut-nakuti saksi di balik jeruji"},
    @{kanji="脅迫する"; furigana="きょうはくする"; arti="mengintimidasi meneror korban dengan pemerasan"},
    @{kanji="恐喝する"; furigana="きょうかつする"; arti="memeras mengancam mengekspos skandal pribadi"},
    @{kanji="強要する"; furigana="きょうようする"; arti="memaksa memaksakan penandatanganan akta sepihak"},
    @{kanji="屈する"; furigana="くっする"; arti="tunduk bertekuk lutut takluk pada tekanan intimidasi"},
    @{kanji="屈服する"; furigana="くっぷくする"; arti="menyerah pasrah mengakui superioritas lawan"},
    @{kanji="従属する"; furigana="じゅうぞくする"; arti="bernaung tunduk di bawah kendali negara induk"},
    @{kanji="追従する"; furigana="ついしょうする"; arti="mengekor membeo apa pun kehendak pucuk pimpinan"},
    @{kanji="媚びる"; furigana="こびる"; arti="merendahkan diri merayu manis mencari muka belas"},
    @{kanji="諂う"; furigana="へつらう"; arti="menjilat menjilat bos demi memuluskan jalan naik"},

    # Diplomacy, Government, Elections & Justice
    @{kanji="躊躇う"; furigana="ためらう"; arti="ragu-ragu bimbang melangkah mengambil keputusan"},
    @{kanji="滞る"; furigana="とどこおる"; arti="tertunda tersendat macet penyelesaian tagihan"},
    @{kanji="怠る"; furigana="おこたる"; arti="lalai teledor mengabaikan kepatuhan prosedur SOP"},
    @{kanji="侮る"; furigana="あなどる"; arti="memandang remeh menyepelekan kehebatan tanding lawan"},
    @{kanji="蔑む"; furigana="さげすむ"; arti="memandang rendah mencemooh menghina martabat sesama"},
    @{kanji="貶める"; furigana="おとしめる"; arti="merendahkan menjatuhkan nama baik harga diri"},
    @{kanji="咎める"; furigana="とがめる"; arti="menegur mempersalahkan kelalaian nurani batin"},
    @{kanji="労る"; furigana="いたわる"; arti="memperlakukan lembut mengasihi raga yang letih"},
    @{kanji="労う"; furigana="ねぎらう"; arti="mengapresiasi memuji jerih lelah keringat rekan kerja"},
    @{kanji="敬う"; furigana="うやまう"; arti="menghormati memuliakan sesepuh dan guru bijak"},
    @{kanji="尊ぶ"; furigana="とうとぶ"; arti="menjunjung tinggi memuliakan nilai kesucian norma"},
    @{kanji="崇める"; furigana="あがめる"; arti="mengagungkan memuja kebesaran sang khalik agung"},
    @{kanji="祀る"; furigana="まつる"; arti="menyemayamkan memuja arwah dewa di altar kuil"},
    @{kanji="崇拝する"; furigana="すうはいする"; arti="memuja mengidolakan sang tokoh secara fanatik"},
    @{kanji="祈願する"; furigana="きがんする"; arti="memanjatkan doa permohonan tulus keselamatan"},
    @{kanji="念願"; furigana="ねんがん"; arti="impian dambaan asa yang sekian lama terpendam"},
    @{kanji="祈祷"; furigana="きとう"; arti="doa persembahyangan ritual memohon keselamatan berkah"},
    @{kanji="厄除け"; furigana="やくよけ"; arti="ritual tolak bala penangkal nasib sial kesialan"},
    @{kanji="兆候"; furigana="ちょうこう"; arti="gejala indikasi tanda-tanda awal terjadinya perubahan"},
    @{kanji="前兆"; furigana="ぜんちょう"; arti="pertanda gejala awal sebelum datangnya gempa bumi"},
    @{kanji="予兆"; furigana="よちょう"; arti="gejala awal tanda-tanda kemunculan badai prahara"},
    @{kanji="予感"; furigana="よかん"; arti="firasat bisikan hati nurani yang terbukti benar"},
    @{kanji="直感"; furigana="ちょっかん"; arti="daya intuisi perasaan spontan tanpa analisis nalar"},
    @{kanji="予言"; furigana="よげん"; arti="ramalan nubuat peristiwa yang bakal terjadi masa depan"},
    @{kanji="占う"; furigana="うらなう"; arti="meramal menerka nasib peruntungan masa depan insan"},
    @{kanji="占拠する"; furigana="せんきょする"; arti="menduduki menguasai fisik gedung balai kota"},
    @{kanji="占領する"; furigana="せんりょうする"; arti="menduduki menginvasi wilayah perbatasan musuh"},
    @{kanji="領有する"; furigana="りょうゆうする"; arti="memiliki menguasai kedaulatan teritorial pulau"},
    @{kanji="領土"; furigana="りょうど"; arti="wilayah daratan teritorial kedaulatan negara hukum"},
    @{kanji="領海"; furigana="りょうかい"; arti="wilayah perairan laut teritorial batas yurisdiksi"},
    @{kanji="領空"; furigana="りょうくう"; arti="ruang udara kedaulatan wilayah dirgantara negeri"},
    @{kanji="領事"; furigana="りょうじ"; arti="pejabat konsul perwakilan diplomatik perdagangan"},
    @{kanji="領事館"; furigana="りょうじかん"; arti="kantor konsulat perwakilan diplomatik negara sahabat"},
    @{kanji="大使"; furigana="たいし"; arti="duta besar kepala perwakilan diplomatik tertinggi"},
    @{kanji="大使館"; furigana="たいしかん"; arti="kantor kedutaan besar negara sahabat perwakilan"},
    @{kanji="外交"; furigana="がいこう"; arti="diplomasi perundingan hubungan antar bangsa dunia"},
    @{kanji="外交官"; furigana="がいこうかん"; arti="diplomat juru runding resmi di panggung dunia"},
    @{kanji="官僚"; furigana="かんりょう"; arti="aparatur birokrat pejabat kementerian pengambil kebijakan"},
    @{kanji="閣僚"; furigana="かくりょう"; arti="jajaran menteri anggota kabinet pemerintahan"},
    @{kanji="首相"; furigana="しゅしょう"; arti="perdana menteri kepala pemerintahan eksekutif"},
    @{kanji="総理大臣"; furigana="そうりだいじん"; arti="perdana menteri jepang kepala kabinet pemerintahan"},
    @{kanji="内閣"; furigana="ないかく"; arti="dewan menteri kabinet pemerintahan kenegaraan"},
    @{kanji="改閣"; furigana="かいかく"; arti="perombakan susunan menteri kabinet reshuffle menteri"},
    @{kanji="総辞職"; furigana="そうじしょく"; arti="pengunduran diri serempak seluruh anggota kabinet"},
    @{kanji="解散"; furigana="かいさん"; arti="pembubaran parlemen dewan menggelar pemilu kilat"},
    @{kanji="総選挙"; furigana="そうせんきょ"; arti="pemilihan umum legislatif akbar pemilu wakil rakyat"},
    @{kanji="投票"; furigana="とうひょう"; arti="pencoblosan pemberian hak suara di bilik pemilu"},
    @{kanji="投票所"; furigana="とうひょうじょ"; arti="tempat pemungutan suara bilik TPS warga"},
    @{kanji="投票箱"; furigana="とうひょうばこ"; arti="kotak suara tempat menghimpun surat coblosan"},
    @{kanji="開票"; furigana="かいひょう"; arti="penghitungan suara rekapitulasi surat coblosan"},
    @{kanji="当選"; furigana="とうせん"; arti="terpilih meraih suara mayoritas memenangkan kursi"},
    @{kanji="落選"; furigana="らくせん"; arti="gugur kalah dalam kontestasi pemungutan suara"},
    @{kanji="議席"; furigana="ぎせき"; arti="kursi perolehan fraksi dewan perwakilan rakyat"},
    @{kanji="与党"; furigana="よとう"; arti="partai politik penguasa koalisi pemerintah"},
    @{kanji="野党"; furigana="やとう"; arti="partai politik oposisi penyeimbang pengontrol"},
    @{kanji="連立"; furigana="れんりつ"; arti="koalisi gabungan kekuatan multipartai berkuasa"},
    @{kanji="連合"; furigana="れんごう"; arti="konfederasi aliansi perserikatan gabungan buruh"},
    @{kanji="同盟"; furigana="どうめい"; arti="pakta aliansi pertahanan militer antar negara"},
    @{kanji="調印"; furigana="ちょういん"; arti="penandatanganan dokumen naskah traktat perjanjian"},
    @{kanji="批准"; furigana="ひじゅん"; arti="ratifikasi pengesahan konvensi internasional dewan"},
    @{kanji="破棄する"; furigana="はきする"; arti="membatalkan memutus sepihak isi kesepakatan kontrak"},
    @{kanji="撤回する"; furigana="てっかいする"; arti="mencabut menarik kembali pernyataan keliru publik"},
    @{kanji="無効"; furigana="むこう"; arti="tidak berlaku batal demi hukum daluarsa statusnya"},
    @{kanji="有効"; furigana="ゆうこう"; arti="sah berlaku memenuhi kaidah syarat kelayakan hukum"},
    @{kanji="失効"; furigana="しっこう"; arti="kehilangan daya laku kedaluwarsa masa tenggatnya"},
    @{kanji="期限切れ"; furigana="きげんぎれ"; arti="lewat tenggat waktu habis masa berlaku legalitas"},
    @{kanji="猶予"; furigana="ゆうよ"; arti="masa tenggang penundaan jatuh tempo kewajiban"},
    @{kanji="恩赦"; furigana="おんしゃ"; arti="pengampunan hukuman grasi pemotongan vonis kepala negara"},
    @{kanji="特赦"; furigana="とくしゃ"; arti="amnesti pengampunan khusus pembebasan pidana hukum"},
    @{kanji="減刑"; furigana="げんけい"; arti="remisi pemotongan masa tahanan narapidana penjara"},
    @{kanji="仮釈放"; furigana="かりしゃくほう"; arti="pembebasan bersyarat narapidana taat disiplin"},

    # Distinctive N2 Adjectives & Nuances
    @{kanji="誇らしい"; furigana="ほこらしい"; arti="merasa bangga berbesar hati membusungkan dada"},
    @{kanji="待ち遠しい"; furigana="まちどおしい"; arti="tak sabar dinanti-nanti kunjungannya tiba"},
    @{kanji="煙たい"; furigana="けむたい"; arti="berasap perih di mata; segan canggung pada atasan"},
    @{kanji="重苦しい"; furigana="おもくるしい"; arti="berat mencekam membebani suasana batin kalbu"},
    @{kanji="堅苦しい"; furigana="かたくるしい"; arti="kaku serba formalitas tiada kelonggaran santai"},
    @{kanji="息苦しい"; furigana="いきぐるしい"; arti="sesak napas pengap ruangan; suasana tertekan"},
    @{kanji="肌寒い"; furigana="はだざむい"; arti="hawa dingin menusuk merindingkan pori kulit"},
    @{kanji="心苦しい"; furigana="こころぐるしい"; arti="merasa tak enak hati sungkan menolak bantuan"},
    @{kanji="決まり悪い"; furigana="きまりわるい"; arti="kikuk canggung serba salah malu tersipu"},
    @{kanji="口惜しい"; furigana="くちおしい"; arti="amat sangat jengkel menyesal atas kegagalan"},
    @{kanji="忌まわしい"; furigana="いまわしい"; arti="kelam menjijikkan penuh aib memori kelam"},
    @{kanji="悩ましい"; furigana="なやましい"; arti="menggoda batin; pelik membingungkan akal"},
    @{kanji="清々しい"; furigana="すがすがしい"; arti="segar bersih sejuk menyegarkan raga sukma"},
    @{kanji="初々しい"; furigana="ういういしい"; arti="lugu polos segar canggung gaya pemula"},
    @{kanji="瑞々しい"; furigana="みずみずしい"; arti="ranum segar berair manis sari buah muda"},
    @{kanji="若々しい"; furigana="わかわかしい"; arti="awet muda berjiwa energik bertenaga prima"},
    @{kanji="騒々しい"; furigana="そうぞうしい"; arti="bising gaduh riuh rendah hiruk pikuk suasana"},
    @{kanji="荒々しい"; furigana="あらあらしい"; arti="kasar beringas buas ombak lautan ganas"},
    @{kanji="勇ましい"; furigana="いさましい"; arti="gagah berani perkasa melangkah ke medan laga"},
    @{kanji="凛々しい"; furigana="りりしい"; arti="gagah rupawan berwibawa memikat kalbu"}
)

$cleanBatch4 = [System.Collections.Generic.List[object]]::new()
$seenBatch4Kanji = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

foreach ($c in $candidatePool4) {
    $k = $c.kanji.Trim()
    if (-not $existingKanjiSet.Contains($k) -and -not $seenBatch4Kanji.Contains($k)) {
        $cleanBatch4.Add($c)
        $seenBatch4Kanji.Add($k) | Out-Null
    }
}

Write-Host "Filtered clean candidates in candidatePool4: $($cleanBatch4.Count)"
