[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$existingJsonRaw = Get-Content -Raw -Encoding UTF8 './data/vocabulary.json'
$existing = $existingJsonRaw | ConvertFrom-Json
Write-Host "Current total existing words in database: $($existing.Length)"

$existingKanjiSet = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
foreach ($item in $existing) {
    if ($item.kanji) {
        $existingKanjiSet.Add($item.kanji.Trim()) | Out-Null
    }
}

$candidatePool3 = @(
    # Science, Nature, Energy & Earth
    @{kanji="膨張"; furigana="ぼうちょう"; arti="ekspansi pemuaian volume gas suhu panas"},
    @{kanji="収縮"; furigana="しゅうしゅく"; arti="pengerutan kontraksi volume akibat dingin"},
    @{kanji="引力"; furigana="いんりょく"; arti="gaya tarik-menarik gravitasi benda angkasa"},
    @{kanji="重力"; furigana="じゅうりょく"; arti="gaya gravitasi bumi daya tarik medan bumi"},
    @{kanji="浮力"; furigana="ふりょく"; arti="gaya apung fluida zat cair ke permukaan"},
    @{kanji="磁気"; furigana="じき"; arti="kemagnetan sifat medan gaya magnetik"},
    @{kanji="電流"; furigana="でんりゅう"; arti="aliran kuat arus muatan listrik kawat"},
    @{kanji="電圧"; furigana="でんあつ"; arti="beda potensial tegangan voltase listrik"},
    @{kanji="回路"; furigana="かいろ"; arti="rangkaian sirkuit skematik kelistrikan"},
    @{kanji="半導体"; furigana="はんどうたい"; arti="komponen semikonduktor mikrochip elektronik"},
    @{kanji="伝導"; furigana="でんどう"; arti="penghantaran konduksi energi kalor panas"},
    @{kanji="放射"; furigana="ほうしゃ"; arti="pemancaran radiasi gelombang energi sinar"},
    @{kanji="放射能"; furigana="ほうしゃのう"; arti="daya radioaktivitas partikel radioaktif"},
    @{kanji="紫外線"; furigana="しがいせん"; arti="radiasi sinar ultraviolet matahari UV"},
    @{kanji="赤外線"; furigana="せきがいせん"; arti="gelombang sinar radiasi inframerah"},
    @{kanji="光合成"; furigana="こうごうせい"; arti="proses fotosintesis klorofil tumbuhan hijau"},
    @{kanji="葉緑素"; furigana="ようりょくそ"; arti="zat pigmen hijau daun klorofil alamiah"},
    @{kanji="生態系"; furigana="せいたいけい"; arti="tatanan ekosistem kesatuan rantai alam hayati"},
    @{kanji="食物連鎖"; furigana="しょくもつれんさ"; arti="mata rantai jaring makanan satwa pemangsa"},
    @{kanji="絶滅"; furigana="ぜつめつ"; arti="kepunahan total musnahnya spesies makhluk"},
    @{kanji="絶滅危惧種"; furigana="ぜつめつきぐしゅ"; arti="spesies satwa langka terancam punah"},
    @{kanji="生息地"; furigana="せいそくち"; arti="habitat alami lingkungan populasi satwa"},
    @{kanji="繁殖"; furigana="はんしょく"; arti="perkembangbiakan reproduksi fauna flora"},
    @{kanji="遺伝"; furigana="いでん"; arti="penurunan sifat hereditas genetika biologis"},
    @{kanji="遺伝子"; furigana="いでんし"; arti="materi pembawa instruksi gen DNA sel"},
    @{kanji="変異"; furigana="へんい"; arti="mutasi loncatan variasi genetik alamiah"},
    @{kanji="進化"; furigana="しんか"; arti="proses evolusi adaptasi spesies organisme"},
    @{kanji="退化"; furigana="たいか"; arti="degenerasi kemunduran fungsi organ tubuh"},
    @{kanji="化石"; furigana="かせき"; arti="fosil bebatuan jejak makhluk purbakala"},
    @{kanji="地層"; furigana="ちそう"; arti="lapisan batuan stratigrafi kerak bumi"},
    @{kanji="地殻"; furigana="ちかく"; arti="litosfer lempeng lapisan kerak terluar bumi"},
    @{kanji="断層"; furigana="だんそう"; arti="patahan sesar geser lempeng bumi gempa"},
    @{kanji="震源"; furigana="しんげん"; arti="hiposentrum titik pusat patahan gempa"},
    @{kanji="震度"; furigana="しんど"; arti="skala intensitas getaran gempa bumi"},
    @{kanji="余震"; furigana="よしん"; arti="gempa susulan frekuensi lemah pasca gempa"},
    @{kanji="溶岩"; furigana="ようがん"; arti="lelehan lava batuan cair pijar kawah"},
    @{kanji="火山灰"; furigana="かざんばい"; arti="hujan abu debu vulkanik semburan kawah"},
    @{kanji="気圧"; furigana="きあつ"; arti="tekanan udara barometer atmosfer atmosferik"},
    @{kanji="高気圧"; furigana="こうきあつ"; arti="daerah antisiklon massa bertekanan tinggi"},
    @{kanji="低気圧"; furigana="ていきあつ"; arti="daerah siklon massa bertekanan rendah badai"},
    @{kanji="前線"; furigana="ぜんせん"; arti="garis front cuaca pertemuan massa udara"},
    @{kanji="寒気"; furigana="かんき"; arti="terpaan massa hawa dingin kutub membekukan"},
    @{kanji="暖気"; furigana="だんき"; arti="hembusan massa hawa hangat tropis musiman"},
    @{kanji="寒波"; furigana="かんぱ"; arti="gelombang hawa dingin menusuk tulang"},
    @{kanji="熱波"; furigana="ねっぱ"; arti="gelombang hawa panas terik membara ekstrem"},
    @{kanji="猛暑"; furigana="もうしょ"; arti="hawa panas terik menyengat musim panas"},
    @{kanji="酷暑"; furigana="こくしょ"; arti="cuaca panas ekstrem memanggang daratan"},
    @{kanji="豪雪"; furigana="ごうせつ"; arti="hujan salju lebat menimbun jalan raya"},
    @{kanji="豪雨"; furigana="ごうう"; arti="hujan badai amat lebat mencurahkan air"},
    @{kanji="集中豪雨"; furigana="しゅうちょうごうう"; arti="hujan badai deras terkonsentrasi lokal"},
    @{kanji="突風"; furigana="とっぷう"; arti="hembusan angin kencang mendadak mengejutkan"},
    @{kanji="竜巻"; furigana="たつまき"; arti="pusaran angin tornado puting beliung corong"},
    @{kanji="落雷"; furigana="らくらい"; arti="sambaran kilat petir menggelegar ke bumi"},
    @{kanji="干ばつ"; furigana="かんばつ"; arti="musim kemarau paceklik kekeringan tanah"},
    @{kanji="飢饉"; furigana="ききん"; arti="kelaparan massal akibat gagal panen paceklik"},
    @{kanji="自給率"; furigana="じきゅうりつ"; arti="tingkat persentase swasembada pasokan pangan"},
    @{kanji="備蓄"; furigana="びちく"; arti="penimbunan cadangan logistik darurat bencana"},
    @{kanji="枯渇"; furigana="こかつ"; arti="kering kerontang tandas cadangan sumber mata air"},
    @{kanji="採取"; furigana="さいしゅ"; arti="pengambilan sampel darah spesimen laboratorium"},
    @{kanji="採掘"; furigana="さいくつ"; arti="penggalian penambangan bijih mineral bumi"},
    @{kanji="精製"; furigana="せいせい"; arti="penyulingan pemurnian fraksi minyak mentah"},
    @{kanji="貯蔵"; furigana="ちょぞう"; arti="penyimpanan persediaan stok di gudang beku"},
    @{kanji="堤防"; furigana="ていぼう"; arti="tanggul penahan air penangkal luapan sungai"},
    @{kanji="治水"; furigana="ちすい"; arti="manajemen rekayasa tata kelola banjir air"},
    @{kanji="灌漑"; furigana="かんがい"; arti="saluran irigasi pengairan persawahan subur"},
    @{kanji="耕作"; furigana="こうさく"; arti="pembajakan penggarapan lahan perkebunan"},
    @{kanji="収穫"; furigana="しゅうかく"; arti="pemetikan panen hasil jerih payah bumi"},
    @{kanji="豊作"; furigana="ほうさく"; arti="panen raya berlimpah ruah lumbung padi"},
    @{kanji="凶作"; furigana="きょうさく"; arti="kegagalan panen paceklik tanaman layu"},
    @{kanji="品種"; furigana="ひんしゅ"; arti="varietas bibit kultivar komoditas tanaman"},
    @{kanji="土壌"; furigana="どじょう"; arti="lapisan tanah subur humus media tanam"},
    @{kanji="肥料"; furigana="ひりょう"; arti="pupuk organik penyubur nutrisi tanaman"},
    @{kanji="農薬"; furigana="のうやく"; arti="cairan pestisida pembasmi hama tanaman"},
    @{kanji="害虫"; furigana="がいちゅう"; arti="serangga hama pengganggu perusak daun"},
    @{kanji="駆除"; furigana="くじょ"; arti="pembasmian tuntas sarang hama rayap tikus"},
    @{kanji="捕獲"; furigana="ほかく"; arti="penangkapan perangkap hewan liar jerat"},
    @{kanji="放流"; furigana="ほうりゅう"; arti="pelepasan tebar bibit ikan ke perairan sungai"},
    @{kanji="飼育"; furigana="しいく"; arti="pemeliharaan peternakan satwa unggas ternak"},
    @{kanji="栽培"; furigana="さいばい"; arti="pembudidayaan bercocok tanam tanaman obat"},
    @{kanji="養殖"; furigana="ようしょく"; arti="budidaya tambak perikanan udang kerang"},
    @{kanji="酪農"; furigana="らくのう"; arti="industri peternakan sapi penghasil susu"},
    @{kanji="畜産"; furigana="ちくさん"; arti="sektor peternakan hewan pedaging komersial"},
    @{kanji="鉱業"; furigana="こうぎょう"; arti="sektor industri tambang eksploitasi mineral"},

    # Industry, Economics & Career Paths
    @{kanji="運輸業"; furigana="うんゆぎょう"; arti="sektor industri ekspedisi logistik kargo"},
    @{kanji="通信業"; furigana="つうしんぎょう"; arti="industri jaringan telekomunikasi internet"},
    @{kanji="金融業"; furigana="きんゆうぎょう"; arti="sektor perbankan industri pasar keuangan"},
    @{kanji="不動産業"; furigana="ふどうさんぎょう"; arti="industri properti real estate pemukiman"},
    @{kanji="建設業"; furigana="けんせつぎょう"; arti="industri konstruksi gedung infrastruktur jalan"},
    @{kanji="製造業"; furigana="せいぞうぎょう"; arti="sektor manufaktur pabrikasi perakitan barang"},
    @{kanji="携わる"; furigana="たずさわる"; arti="berkiprah berkecimpung aktif dalam bidang itu"},
    @{kanji="営む"; furigana="いとなむ"; arti="mengelola mengoperasikan roda bisnis dagang"},
    @{kanji="挑む"; furigana="いどむ"; arti="menantang mengadu keberanian hadapi rintangan"},
    @{kanji="臨む"; furigana="のぞむ"; arti="menghadapi momentum sidang krusial penuh harap"},
    @{kanji="拒む"; furigana="こばむ"; arti="menampik menolak keras ajakan kompromi licik"},
    @{kanji="委ねる"; furigana="ゆだねる"; arti="mempercayakan melimpahkan wewenang nasib pada ahlinya"},
    @{kanji="託す"; furigana="たくす"; arti="menitipkan harapan amanah masa depan ke generasi muda"},
    @{kanji="委託する"; furigana="いたくする"; arti="mensubkontrakkan pengerjaan modul proyek"},
    @{kanji="受託する"; furigana="じゅたくする"; arti="menerima amanat kontrak pesanan klien"},
    @{kanji="譲渡"; furigana="じょうと"; arti="pemindahtanganan transfer lisensi kepemilikan"},
    @{kanji="承継"; furigana="しょうけい"; arti="suksesi pelanjutan tongkat estafet bisnis keluarga"},
    @{kanji="継承"; furigana="けいしょう"; arti="pewarisan pelestarian nilai budaya leluhur nusa"},
    @{kanji="襲来"; furigana="しゅうらい"; arti="serbuan kedatangan badai taufan memorak-porandakan"},
    @{kanji="来襲"; furigana="らいしゅう"; arti="serangan invasi mendadak armada musuh di perbatasan"},
    @{kanji="侵略"; furigana="しんりゃく"; arti="invasi agresi pendudukan tanah kedaulatan bangsa"},
    @{kanji="侵害する"; furigana="しんがいする"; arti="mencederai melanggar privasi hak asasi cipta"},
    @{kanji="干渉"; furigana="かんしょう"; arti="intervensi campur tangan kedaulatan pihak lain"},
    @{kanji="介入"; furigana="かいにゅう"; arti="keterlibatan aktif menengahi konflik kebuntuan"},
    @{kanji="調停"; furigana="ちょうてい"; arti="rekonsiliasi mediasi pihak ketiga berdamai"},
    @{kanji="親善"; furigana="しんぜん"; arti="hubungan diplomatik persahabatan tali asih kenegaraan"},
    @{kanji="親睦"; furigana="しんぼく"; arti="mempererat tali silaturahmi keakraban kerabat"},
    @{kanji="懇親"; furigana="こんしん"; arti="malam ramah tamah menjalin relasi akrab rekan kerja"},
    @{kanji="歓談"; furigana="かんだん"; arti="berbincang-bincang hangat penuh kegembiraan santai"},
    @{kanji="雑談"; furigana="ざつだん"; arti="obrolan santai ngobrol ngalor ngidul pelepas penat"},
    @{kanji="談笑"; furigana="だんしょう"; arti="bersenda gurau riang jenaka dalam perjumpaan"},
    @{kanji="談合"; furigana="だんごう"; arti="kongkalikong persekongkolan tender lelang rahasia"},
    @{kanji="密議"; furigana="みつぎ"; arti="musyawarah tertutup konspirasi balik layar"},
    @{kanji="密談"; furigana="みつだん"; arti="percakapan privat empat mata membicarakan strategi"},
    @{kanji="密輸"; furigana="みつゆ"; arti="penyelundupan komoditas ilegal lintas batas negara"},
    @{kanji="密航"; furigana="みっこう"; arti="pelayaran gelap imigran ilegal menyusup kapal"},
    @{kanji="不法"; furigana="ふほう"; arti="tindakan melawan hukum liar tiada legalitas resmi"},
    @{kanji="違法"; furigana="いほう"; arti="perbuatan terlarang melanggar pasal undang-undang"},
    @{kanji="脱法"; furigana="だっぽう"; arti="pengelabuan mengeksploitasi celah kelemahan hukum"},
    @{kanji="偽造"; furigana="ぎぞう"; arti="pemalsuan rekayasa lembar surat identitas paspor"},
    @{kanji="捏造"; furigana="ねつぞう"; arti="fabrikasi mengarang kebohongan memutarbalikkan data"},
    @{kanji="詐欺"; furigana="さぎ"; arti="tindak penipuan licik mengelabui korban uang"},
    @{kanji="横領"; furigana="おうりょう"; arti="penggelapan korupsi uang kas rekening instansi"},
    @{kanji="汚職"; furigana="おしょく"; arti="tindak korupsi penyalahgunaan wewenang kursi jabatan"},
    @{kanji="収賄"; furigana="しゅうわい"; arti="penerimaan suap gratifikasi sogokan uang pelicin"},
    @{kanji="贈賄"; furigana="ぞうわい"; arti="pemberian suap gratifikasi menyogok pejabat"},
    @{kanji="賄賂"; furigana="わいろ"; arti="uang pelicin sogokan amplop haram melancarkan urusan"},
    @{kanji="摘発"; furigana="てきはつ"; arti="penggerebekan penindakan oknum pelanggar hukum"},
    @{kanji="押収"; furigana="おうしゅう"; arti="penyitaan barang bukti hasil kejahatan narkoba"},
    @{kanji="没収"; furigana="ぼっしゅう"; arti="perampasan sita aset koruptor untuk kas negara"},
    @{kanji="弁済"; furigana="べんさい"; arti="pelunasan penebusan seluruh kewajiban utang piutang"},
    @{kanji="完済"; furigana="かんさい"; arti="lunas tuntas seluruh tagihan angsuran kredit"},

    # Mind, Psychology & Emotion Nuances
    @{kanji="陶酔"; furigana="とうすい"; arti="mabuk kepayang terbuai ekstasi keindahan melodi"},
    @{kanji="畏敬"; furigana="いけい"; arti="takzim kagum segan memandang keagungan alam semesta"},
    @{kanji="敬意"; furigana="けいい"; arti="rasa hormat respek mendalam atas dedikasi teladan"},
    @{kanji="謝意"; furigana="しゃい"; arti="pernyataan terima kasih penghargaan tulus jasa"},
    @{kanji="敵意"; furigana="てきい"; arti="sentimen permusuhan itikad dendam yang membara"},
    @{kanji="悪意"; furigana="あくい"; arti="itikad buruk niat jahat mencelakakan sesama"},
    @{kanji="善意"; furigana="ぜんい"; arti="itikad baik kemurnian hati sukarela menolong"},
    @{kanji="好意"; furigana="こうい"; arti="perasaan simpati suka ketertarikan hangat sahabat"},
    @{kanji="殺意"; furigana="さつい"; arti="niat menghabisi nyawa dorongan amarah memuncak"},
    @{kanji="自責"; furigana="じせき"; arti="rasa bersalah mencela menyesali kelemahan diri"},
    @{kanji="自負"; furigana="じふ"; arti="kebanggaan harga diri percaya atas kapasitas karya"},
    @{kanji="自惚れ"; furigana="うぬぼれ"; arti="terlalu membanggakan diri narsisme sombong"},
    @{kanji="自重"; furigana="じちょう"; arti="menahan diri mawas diri menjaga kehormatan nama baik"},
    @{kanji="自制"; furigana="じせい"; arti="pengendalian diri meredam gejolak amarah emosi"},
    @{kanji="自粛"; furigana="じしゅく"; arti="menahan diri berdiam sukarela saat masa berkabung"},
    @{kanji="自衛"; furigana="じえい"; arti="bela diri perlindungan proteksi keselamatan raga"},
    @{kanji="自立"; furigana="じりつ"; arti="kemandirian berdiri di atas kaki sendiri nafkah"},
    @{kanji="自律"; furigana="じりつ"; arti="kedisiplinan otonom mematuhi kompas moral diri"},
    @{kanji="自主"; furigana="じしゅ"; arti="prakarsa otonom kesadaran berbuat tanpa disuruh"},
    @{kanji="独創"; furigana="どくそう"; arti="orisinalitas daya cipta kreasi unik tanpa meniru"},
    @{kanji="独自"; furigana="どくじ"; arti="karakteristik khas otentik gaya kreasi tersendiri"},
    @{kanji="独占"; furigana="どくせん"; arti="monopoli penguasaan sepihak seluruh pangsa produk"},
    @{kanji="専属"; furigana="せんぞく"; arti="ikatan kontrak kerja eksklusif di satu agensi"},
    @{kanji="専念"; furigana="せんねん"; arti="mencurahkan segenap jiwa fokus pada satu target"},
    @{kanji="没頭"; furigana="ぼっとう"; arti="tenggelam asyik khusyuk larut dalam karya riset"},
    @{kanji="傾倒"; furigana="けいとう"; arti="sangat mengagumi mencintai ajaran falsafah sang guru"},
    @{kanji="盲信"; furigana="もうしん"; arti="kepercayaan buta dogma tanpa nalar kritis"},
    @{kanji="狂信"; furigana="きょうしん"; arti="fanatisme ekstrem buta merelakan segalanya"},
    @{kanji="偏愛"; furigana="へんあい"; arti="cinta berat sebelah kecintaan pilih kasih condong"},
    @{kanji="えこひいき"; furigana="えこひいき"; arti="perlakuan pilih kasih diskriminatif menganakemaskan"},
    @{kanji="優遇"; furigana="ゆうぐう"; arti="perlakuan hak istimewa fasilitas kelas wahid"},
    @{kanji="冷遇"; furigana="れいぐう"; arti="perlakuan dingin diskriminatif ditelantarkan di sudut"},
    @{kanji="迫害"; furigana="はくがい"; arti="tindakan persekusi penzaliman intimidasi kelompok"},
    @{kanji="弾圧"; furigana="だんあつ"; arti="pemberangusan represif kekuasaan terhadap suara rakyat"},
    @{kanji="糾弾"; furigana="きゅうだん"; arti="kecaman protes keras menuntut tanggung jawab moral"},
    @{kanji="告発"; furigana="こくはつ"; arti="pengaduan pembongkaran skandal manipulasi tender"},
    @{kanji="暴露"; furigana="ばくろ"; arti="pembocoran pengungkapan rahasia gelap ke publik"},
    @{kanji="発覚"; furigana="はっかく"; arti="terbongkarnya terkuaknya kedok kejahatan tersembunyi"},
    @{kanji="露呈"; furigana="ろてい"; arti="tersingkapnya kelemahan cacat cela sistem di permukaan"},
    @{kanji="判明"; furigana="はんめい"; arti="terbukti teridentifikasi dengan jelas jati dirinya"},
    @{kanji="究明"; furigana="きゅうめい"; arti="pengusutan tuntas penyelidikan menguak misteri tabir"},
    @{kanji="解明"; furigana="かいめい"; arti="pemecahan penyingkapan teka-teki misteri ilmiah"},
    @{kanji="究極"; furigana="きゅうきょく"; arti="puncak esensi pamungkas kesempurnaan tertinggi"},
    @{kanji="極上"; furigana="ごくじょう"; arti="mutu kualitas terbaik jempolan tanpa tanding"},
    @{kanji="一流"; furigana="いちりゅう"; arti="kaliber kelas satu papan atas maestro ternama"},
    @{kanji="二流"; furigana="にりゅう"; arti="kaliber kelas menengah standar umum rata-rata"},
    @{kanji="三流"; furigana="さんりゅう"; arti="kualitas kelas teri rendahan tiada berbobot"},
    @{kanji="粗悪"; furigana="そあく"; arti="kualitas jelek kasar tiruan abal-abal lekas rusak"},
    @{kanji="優良"; furigana="ゆうりょう"; arti="sangat baik bonafide sehat neraca keuangannya"},
    @{kanji="良好"; furigana="りょうこう"; arti="kondisi fisik bugar prima memuaskan perkembangannya"},
    @{kanji="好調"; furigana="こうちょう"; arti="performa prima melesat tajam grafik capaian"},
    @{kanji="不調"; furigana="ふちょう"; arti="kondisi kurang prima mengalami penurunan staminanya"},
    @{kanji="難航"; furigana="なんこう"; arti="perjalanan tersendat alot menemui kendala ombak"},
    @{kanji="停滞"; furigana="ていたい"; arti="stagnan jalan di tempat mandek laju pergerakan"},
    @{kanji="足踏み"; furigana="あしぶみ"; arti="tertahan jalan di tempat tiada penambahan progres"},
    @{kanji="膠着"; furigana="こうちゃく"; arti="kondisi kebuntuan deadlock sengit tiada pemenang"},
    @{kanji="行き詰まり"; furigana="いきづまり"; arti="menemui jalan buntu tiada alternatif ide solusi"},
    @{kanji="突破"; furigana="とっぱ"; arti="pendobrakan menembus rekor melampaui batasan"},
    @{kanji="打開"; furigana="だかい"; arti="pemecahan mendobrak jalan keluar dari krisis sulit"},
    @{kanji="起死回生"; furigana="きしかいせい"; arti="kebangkitan spektakuler membalikkan keterpurukan"},

    # More Advanced Action Verbs & Compound Verbs
    @{kanji="打ち切る"; furigana="うちきる"; arti="menghentikan menyetop penayangan siaran sepihak"},
    @{kanji="切り上げる"; furigana="きりあげる"; arti="menyudahi mengakhiri rapat tepat pada waktunya"},
    @{kanji="切り抜ける"; furigana="きりぬける"; arti="berhasil lolos menerobos kepungan marabahaya"},
    @{kanji="引き下げる"; furigana="ひきさげる"; arti="menurunkan memangkas suku bunga acuan pasar"},
    @{kanji="引き上げる"; furigana="ひきあげる"; arti="menaikkan menaikkan tarif batas minimum upah"},
    @{kanji="見合わせる"; furigana="みあわせる"; arti="menunda menangguhkan keberangkatan akibat badai"},
    @{kanji="見せつける"; furigana="みせつける"; arti="memamerkan unjuk superioritas kekuatan fisik"},
    @{kanji="見せかける"; furigana="みせかける"; arti="berpura-pura berpura-pura menyamar bak penderma"},
    @{kanji="取り戻す"; furigana="とりもどす"; arti="merebut kembali memulihkan kejayaan masa lalu"},
    @{kanji="取り立てる"; furigana="とりたてる"; arti="menagih utang menonjolkan kasus secara spesial"},
    @{kanji="取り寄せる"; furigana="とりよせる"; arti="memesan mendatangkan barang impor dari negeri seberang"},
    @{kanji="持ち込む"; furigana="もちこむ"; arti="membawa masuk barang selundupan ke dalam kabin"},
    @{kanji="持ち直す"; furigana="もちなおす"; arti="berangsur pulih membaik kondisi kesehatan pasien"},
    @{kanji="立て替える"; furigana="たてかえる"; arti="membayari menalangi terlebih dahulu biaya tiket"},
    @{kanji="買い換える"; furigana="かいかえる"; arti="membeli mengganti perabot lama dengan baru"},
    @{kanji="乗り換える"; furigana="のりかえる"; arti="beralih berganti langganan operator seluler lain"},
    @{kanji="生まれ変わる"; furigana="うまれかわる"; arti="terlahir kembali menjadi pribadi baru yang bersih"},
    @{kanji="立ち直る"; furigana="たちなおる"; arti="bangkit tegar bangkit kembali dari keterpurukan"},
    @{kanji="引き分ける"; furigana="ひきわける"; arti="bermain imbang seri tanpa pemenang di laga final"},
    @{kanji="寄りかかる"; furigana="よりかかる"; arti="bersandar menyandarkan punggung ke tiang tembok"},
    @{kanji="頼り切る"; furigana="たよりきる"; arti="bergantung sepenuhnya pasrah pada bantuan orang"},
    @{kanji="言い兼ねる"; furigana="いいかねる"; arti="merasa sungkan berat hati hendak berterus terang"},
    @{kanji="決め兼ねる"; furigana="きめかねる"; arti="bimbang sukar memutuskan pilihan di antara dua opsi"},

    # Transportation, Safety, Infrastructure & Legal Disputes
    @{kanji="包装"; furigana="ほうそう"; arti="pengemasan pembungkusan paket kado hadiah"},
    @{kanji="梱包"; furigana="こんぽう"; arti="pengepakan bal kardus logistik pengiriman"},
    @{kanji="運搬"; furigana="うんぱん"; arti="pengangkutan pemindahan muatan barang berat"},
    @{kanji="搬送"; furigana="はんそう"; arti="transfer evakuasi pasien ke ruang ICU ambulans"},
    @{kanji="運賃"; furigana="うんちん"; arti="ongkos tarif tiket perjalanan transportasi"},
    @{kanji="経路"; furigana="けいろ"; arti="rute trayek lintasan jalan tempuh perjalanan"},
    @{kanji="順路"; furigana="じゅんろ"; arti="rute arah jalur sirkulasi pengunjung pameran"},
    @{kanji="迂回"; furigana="うかい"; arti="pengalihan jalan memutar menghindari kemacetan"},
    @{kanji="遠回り"; furigana="とおまわり"; arti="mengambil jalan memutar rute lebih jauh"},
    @{kanji="近道"; furigana="ちかみち"; arti="jalan pintas memotong waktu tempuh rute"},
    @{kanji="踏切"; furigana="ふみきり"; arti="perlintasan palang pintu rel kereta api"},
    @{kanji="歩道"; furigana="ほどう"; arti="trotoar pedestrian khusus pejalan kaki"},
    @{kanji="車道"; furigana="しゃどう"; arti="badan jalan jalur lintasan mobil motor"},
    @{kanji="高速道路"; furigana="こうそくどうろ"; arti="jalan tol bebas hambatan lintas provinsi"},
    @{kanji="料金所"; furigana="りょうきんじょ"; arti="gerbang loket pembayaran tarif tol jalan"},
    @{kanji="車線"; furigana="しゃせん"; arti="marka garis lajur pembagian badan jalan"},
    @{kanji="制限速度"; furigana="せいげんそくど"; arti="batas rambu kecepatan maksimum kendaraan"},
    @{kanji="免許証"; furigana="めんきょしょう"; arti="surat kartu tanda izin mengemudi SIM legal"},
    @{kanji="車検"; furigana="しゃけん"; arti="uji emisi kelaikan jalan kendaraan berkala"},
    @{kanji="燃費"; furigana="ねんぴ"; arti="tingkat efisiensi pemakaian bahan bakar bensin"},
    @{kanji="給油"; furigana="きゅうゆ"; arti="pengisian bahan bakar solar bensin di SPBU"},
    @{kanji="パンク"; furigana="ぱんく"; arti="ban kempes meletus terkena ranjau paku tajam"},
    @{kanji="追突"; furigana="ついとつ"; arti="tabrakan beruntun menyenggol dari arah belakang"},
    @{kanji="衝突"; furigana="しょうとつ"; arti="tabrakan tubrukan benturan keras dua kubu"},
    @{kanji="接触"; furigana="せっしょく"; arti="gesekan kontak fisik senggolan bodi mobil"},
    @{kanji="転倒"; furigana="てんとう"; arti="terjatuh tersungkur terpeleset licin jalan"},
    @{kanji="転落"; furigana="てんらく"; arti="terperosok jatuh ke dalam lembah jurang terjal"},
    @{kanji="墜落"; furigana="ついらく"; arti="terhempas jatuh pesawat terbang dari angkasa"},
    @{kanji="沈没"; furigana="ちんぼつ"; arti="karam tenggelam kapal feri ke dasar samudra"},
    @{kanji="座礁"; furigana="ざしょう"; arti="kandas terdampar lambung kapal membentur karang"},
    @{kanji="炎上"; furigana="えんじょう"; arti="terbakar kobaran api hebat; diserbu kritik netizen"},
    @{kanji="延焼"; furigana="えんしょう"; arti="perambatan kobaran api ke bangunan tetangga"},
    @{kanji="全焼"; furigana="ぜんしょう"; arti="hangus ludes terbakar rata dengan tanah"},
    @{kanji="半焼"; furigana="はんしょう"; arti="terbakar separuh bagian konstruksi rumah"},
    @{kanji="鎮火"; furigana="ちんか"; arti="pemadaman tuntas bara api oleh tim pemadam"},
    @{kanji="消火器"; furigana="しょうかき"; arti="tabung alat pemadam api ringan darurat APAR"},
    @{kanji="非常口"; furigana="ひじょうぐち"; arti="pintu keluar darurat evakuasi bencana gedung"},
    @{kanji="防災"; furigana="ぼうさい"; arti="mitigasi pencegahan penanggulangan risiko bencana"},
    @{kanji="耐震"; furigana="たいしん"; arti="konstruksi bangunan tahan guncangan gempa bumi"},
    @{kanji="避雷針"; furigana="ひらいしん"; arti="tiang instalasi penangkal sambaran petir atap"},
    @{kanji="警戒"; furigana="けいかい"; arti="kewaspadaan kesiapsiagaan mengantisipasi bahaya"},
    @{kanji="巡回"; furigana="じゅんかい"; arti="patroli keliling ronda keamanan pos kamling"},
    @{kanji="監視"; furigana="かんし"; arti="pengawasan pengintaian intensif kamera pengintai"},
    @{kanji="追跡"; furigana="ついせき"; arti="pelacakan perburuan sinyal jejak pelaku kabur"},
    @{kanji="尾行"; furigana="びこう"; arti="pembuntutan menguntit diam-diam dari belakang"},
    @{kanji="潜入"; furigana="せんにゅう"; arti="penyusupan infiltrasi mata-mata ke sarang lawan"},
    @{kanji="盗聴"; furigana="とうちょう"; arti="penyadapan komunikasi pembicaraan saluran telepon"},
    @{kanji="盗撮"; furigana="とうさつ"; arti="perekaman gambar foto rahasia secara ilegal"},
    @{kanji="隠蔽"; furigana="いんぺい"; arti="penutupan manipulasi penyembunyian barang bukti"},
    @{kanji="告白"; furigana="こくはく"; arti="pengakuan jujur terus terang rahasia cinta nurani"},
    @{kanji="懺悔"; furigana="ざんげ"; arti="penyesalan pertobatan tulus atas dosa silam"},
    @{kanji="償い"; furigana="つぐない"; arti="penebusan pembayaran kompensasi dosa kekhilafan"},
    @{kanji="慰謝料"; furigana="いしゃりょう"; arti="uang ganti rugi kompensasi luka trauma batin"},
    @{kanji="養育費"; furigana="よういくひ"; arti="uang tunjangan nafkah pemeliharaan nafkah anak"},
    @{kanji="扶養"; furigana="ふよう"; arti="tanggungan pemeliharaan memberi nafkah keluarga"},
    @{kanji="扶助"; furigana="ふじょ"; arti="bantuan santunan jaminan sosial perlindungan"},
    @{kanji="恩恵"; furigana="おんけい"; arti="berkah limpahan manfaat anugerah alam raya"},
    @{kanji="報復"; furigana="ほうふく"; arti="aksi serangan balasan pembalasan dendam perang"},
    @{kanji="復讐"; furigana="ふくしゅう"; arti="penuntasan dendam kesumat sakit hati masa lalu"},
    @{kanji="因縁"; furigana="いんねん"; arti="tali ikatan takdir misterius jalinan masa lalu"},
    @{kanji="因果"; furigana="いんが"; arti="hukum sebab akibat hukum karma perbuatan insan"},
    @{kanji="宿命"; furigana="しゅくめい"; arti="garis suratan takdir mutlak tak terelakkan"},
    @{kanji="運命"; furigana="うんめい"; arti="garis takdir perjalanan nasib liku kehidupan"},
    @{kanji="命運"; furigana="めいうん"; arti="pertaruhan masa depan nasib jatuh bangunnya negeri"}
)

$cleanBatch3 = [System.Collections.Generic.List[object]]::new()
$seenBatch3Kanji = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

foreach ($c in $candidatePool3) {
    $k = $c.kanji.Trim()
    if (-not $existingKanjiSet.Contains($k) -and -not $seenBatch3Kanji.Contains($k)) {
        $cleanBatch3.Add($c)
        $seenBatch3Kanji.Add($k) | Out-Null
    }
}

Write-Host "Filtered clean candidates in candidatePool3: $($cleanBatch3.Count)"
