[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$existingJsonRaw = Get-Content -Raw -Encoding UTF8 './data/vocabulary.json'
$existing = $existingJsonRaw | ConvertFrom-Json
Write-Host "Current total existing words in database: $($existing.Length)"

$existingKanjiSet = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
foreach ($item in $existing) {
    if ($item.kanji) {
        $existingKanjiSet.Add($item.kanji.Trim()) | Out-Null
    }
}

$candidatePool5 = @(
    # Body Movements, Posture, Senses & Physical Expressions
    @{kanji="仰ぐ"; furigana="あおぐ"; arti="menengadah memandang langit; memohon arahan nasihat"},
    @{kanji="俯く"; furigana="うつむく"; arti="menundukkan kepala murung malu tersipu kalbu"},
    @{kanji="頷く"; furigana="うなずく"; arti="mengangguk-angguk tanda paham sepakat menyetujui"},
    @{kanji="跨ぐ"; furigana="またぐ"; arti="melangkahi genangan air parit melompati pagar"},
    @{kanji="躓く"; furigana="つまずく"; arti="tersandung batu terjal; tersendat gagal langkah karir"},
    @{kanji="潜る"; furigana="くぐる"; arti="menyelinap menyusup melewati celah gerbang sempit"},
    @{kanji="潜水する"; furigana="せんすいする"; arti="menyelam ke kedalaman samudra dengan tabung oksigen"},
    @{kanji="浮上する"; furigana="ふじょうする"; arti="muncul ke permukaan air; mencuat ke pusaran publik"},
    @{kanji="沈下する"; furigana="ちんかする"; arti="amblas penurunan struktur fondasi tanah permukaan"},
    @{kanji="傾く"; furigana="かたむく"; arti="miring condong ke sisi; merosot neraca keuangan"},
    @{kanji="傾斜する"; furigana="けいしゃする"; arti="miring membentuk sudut lereng kecuraman tajam"},
    @{kanji="倒壊する"; furigana="とうかいする"; arti="roboh luluh lantak diguncang guncangan lindu"},
    @{kanji="崩落する"; furigana="ほうらくする"; arti="ambrol runtuh bebatuan atap dinding terowongan"},
    @{kanji="剥がれる"; furigana="はがれる"; arti="mengelupas terlepas lapisan cat plester dinding"},
    @{kanji="剥ぎ取る"; furigana="はぎとる"; arti="merenggut mengelupas paksa selubung penutup kulit"},
    @{kanji="削る"; furigana="けずる"; arti="menyerut meraut batang pensil; memangkas anggaran belanja"},
    @{kanji="擦る"; furigana="こする"; arti="menggosok mengusap kelopak mata gatal; menyikat wajan"},
    @{kanji="摩耗する"; furigana="まもうする"; arti="aus tergerus gesekan komponen mesin berputar"},
    @{kanji="軋む"; furigana="きしむ"; arti="berderit berderik lantai papan kayu diinjak beban"},
    @{kanji="軋轢"; furigana="あつれき"; arti="friksi pergesekan ketegangan konflik persahabatan"},
    @{kanji="揉める"; furigana="もめる"; arti="berselisih bersitegang adu mulut memperdebatkan hak"},
    @{kanji="揉み合う"; furigana="もみあう"; arti="dorong-dorongan berdesak-desakan di tengah kerumunan massa"},
    @{kanji="掻き分ける"; furigana="かきわける"; arti="menyibak kerumunan khalayak; menembus belantara ilalang"},
    @{kanji="押し寄せる"; furigana="おしよせる"; arti="bergelombang menyerbu membanjiri berbondong-bondong datang"},
    @{kanji="押し切る"; furigana="おしきる"; arti="memaksakan kehendak menolak protes suara minoritas"},
    @{kanji="押し通す"; furigana="おしとおす"; arti="bersikukuh mempertahankan draf peraturan hingga tuntas"},
    @{kanji="踏み倒す"; furigana="ふみたおす"; arti="mangkir kabur menghindari kewajiban melunasi utang piutang"},
    @{kanji="踏み荒らす"; furigana="ふみあらす"; arti="menginjak-injak merusak petak kebun tanaman bunga"},
    @{kanji="荒廃する"; furigana="こうはいする"; arti="porak-poranda rusak telantar puing kota perang"},
    @{kanji="疲弊する"; furigana="ひへいする"; arti="terkuras tenaganya lunglai; kelesuan ekonomi lesu"},
    @{kanji="衰退する"; furigana="すいたいする"; arti="mengalami kemerosotan penurunan kejayaan dinasti"},
    @{kanji="衰える"; furigana="おとろえる"; arti="melemah menyusut stamina fisik seiring bertambahnya usia"},
    @{kanji="萎縮する"; furigana="いしゅくする"; arti="menciut nyali gemetar tertekan akibat hardikan"},
    @{kanji="縮こまる"; furigana="ちぢこまる"; arti="meringkuk kedinginan menggigil; ciut rasa percaya diri"},
    @{kanji="身構える"; furigana="みがまえる"; arti="memasang kuda-kuda siaga menepis ancaman marabahaya"},
    @{kanji="待ち構える"; furigana="まちかまえる"; arti="bersiap menyongsong menghadang tibanya tamu lawan"},
    @{kanji="構える"; furigana="かまえる"; arti="memasang sikap postur; membuka gerai lapak dagangan"},
    @{kanji="立ち振る舞い"; furigana="たちふるまい"; arti="gerak-gerik tata krama pembawaan santun terpelajar"},
    @{kanji="物腰"; furigana="ものごし"; arti="sikap pembawaan tutur kata yang lembut menyejukkan"},
    @{kanji="物怖じ"; furigana="ものおじ"; arti="gentar ragu takut berhadapan dengan orang asing"},
    @{kanji="物々しい"; furigana="ものものしい"; arti="ketat mencekam pengawalan persenjataan lengkap serdadu"},
    @{kanji="物悲しい"; furigana="ものがなしい"; arti="sendu melankolis sayu memilukan hati petang hari"},
    @{kanji="物寂しい"; furigana="ものさびしい"; arti="lengang sepi sunyi mencekam sudut gang kota tua"},
    @{kanji="空しい"; furigana="むなしい"; arti="hampa kosong sia-sia tiada membuahkan faedah"},
    @{kanji="儚い"; furigana="はかない"; arti="fana singkat rapuh lenyap sekejap mata mimpi"},
    @{kanji="脆い"; furigana="もろい"; arti="rapuh lekas retak; lekas menangis berhati peka"},
    @{kanji="渋い"; furigana="しぶい"; arti="sepat rasa buah kesemek mentah; klasik berselera elegan"},
    @{kanji="生臭い"; furigana="なまぐさい"; arti="bau anyir amis ikan segar; kotor penuh skandal"},
    @{kanji="香ばしい"; furigana="こうばしい"; arti="aroma harum wangi menggoda selera biji kopi sangrai"},
    @{kanji="芳しい"; furigana="かんばしい"; arti="harum semerbak kasturi; memuaskan capaian hasilnya"},
    @{kanji="鬱陶しい"; furigana="うっとうしい"; arti="pengap gerah cuaca; membosankan menjengkelkan pikiran"},
    @{kanji="泥臭い"; furigana="どろくさい"; arti="kental aroma lumpur udik; gigih berpeluh keringat kasar"},
    @{kanji="田舎臭い"; furigana="いなかくさい"; arti="kedaerahan bersahaja udik belum luwes gaya metropolis"},
    @{kanji="胡散臭い"; furigana="うさんくさい"; arti="mencurigakan berbau janggal tipu daya gelagatnya"},
    @{kanji="照れくさい"; furigana="てれくさい"; arti="tersipu malu kikuk canggung saat dipuji di depan umum"},
    @{kanji="泥沼化"; furigana="どろぬまか"; arti="berlarut-larutnya konflik sengketa tanpa ujung terang"},

    # Economics, Markets & Securities
    @{kanji="銘柄"; furigana="めいがら"; arti="merek komoditas unggulan; emiten saham bursa efek"},
    @{kanji="株式"; furigana="かぶしき"; arti="perseroan terbatas bukti kepemilikan sero saham"},
    @{kanji="配当"; furigana="はいとう"; arti="pembagian keuntungan dividen laba pemegang saham"},
    @{kanji="割当"; furigana="わりあて"; arti="alokasi penjatahan jatah kuota bahan baku impor"},
    @{kanji="利子"; furigana="りし"; arti="bunga simpanan rekening tabungan perbankan konvensional"},
    @{kanji="利息"; furigana="りそく"; arti="bunga pinjaman tagihan pembiayaan kredit debitur"},
    @{kanji="利潤"; furigana="りじゅん"; arti="marjin keuntungan bersih laba komersial korporasi"},
    @{kanji="収益"; furigana="しゅうえき"; arti="total pemasukan pendapatan laba operasional usaha"},
    @{kanji="損失"; furigana="そんしつ"; arti="kerugian finansial beban penyusutan kerusakan aset"},
    @{kanji="債権"; furigana="さいけん"; arti="hak tagih klaim piutang kepada pihak berutang"},
    @{kanji="債務"; furigana="さいむ"; arti="beban kewajiban utang cicilan yang wajib disetor"},
    @{kanji="債権者"; furigana="さいけんしゃ"; arti="kreditur pihak pemilik modal piutang pinjaman"},
    @{kanji="債務者"; furigana="さいむしゃ"; arti="debitur pihak yang berkewajiban melunasi utang"},
    @{kanji="担保"; furigana="たんぽ"; arti="barang agunan jaminan sertifikat hak tanggungan kredit"},
    @{kanji="抵当"; furigana="ていとう"; arti="hak tanggungan hipotik atas aset tak bergerak"},
    @{kanji="競売"; furigana="きょうばい"; arti="penjualan lelang eksekusi sita aset di balai lelang"},
    @{kanji="入札"; furigana="にゅうさつ"; arti="penyampaian draf penawaran lelang tender proyek"},
    @{kanji="落札"; furigana="らくさつ"; arti="kemenangan menyabet memenangkan tender lelang proyek"},
    @{kanji="敷金"; furigana="しききん"; arti="uang deposit jaminan pemeliharaan sewa hunian"},
    @{kanji="礼金"; furigana="れいきん"; arti="uang tanda apresiasi hadiah sewa kepada pemilik kamar"},
    @{kanji="共益費"; furigana="きょうえきひ"; arti="iuran operasional sarana fasilitas bersama gedung"},
    @{kanji="管理費"; furigana="かんりひ"; arti="biaya iuran pengelolaan lingkungan keamanan hunian"},
    @{kanji="仲介"; furigana="ちゅうかい"; arti="jasa mediasi perantara transaksi jual beli properti"},
    @{kanji="手数料"; furigana="てすうりょう"; arti="ongkos biaya komisi administrasi pengurusan transaksi"},
    @{kanji="印紙"; furigana="いんし"; arti="meterai tempel bukti pelunasan pajak bea dokumen"},
    @{kanji="印紙税"; furigana="いんしぜい"; arti="pajak bea meterai pengesahan lembar surat perjanjian"},
    @{kanji="源泉徴収"; furigana="げんせんちょうしゅう"; arti="pemotongan pajak penghasilan pph langsung dari gaji"},
    @{kanji="確定申告"; furigana="かくていしんこく"; arti="pelaporan SPT formulir pajak tahunan wajib pajak"},
    @{kanji="納税"; furigana="のうぜい"; arti="penyetoran pembayaran pajak warga ke kas perbendaharaan"},
    @{kanji="脱税"; furigana="だつぜい"; arti="kejahatan manipulasi penggelapan pajak penghasilan"},
    @{kanji="節税"; furigana="せつぜい"; arti="strategi efisiensi penghematan pajak secara legal"},
    @{kanji="課税"; furigana="かぜい"; arti="pengenaan penetapan tarif pungutan pajak barang"},
    @{kanji="非課税"; furigana="ひかぜい"; arti="fasilitas pembebasan bebas pajak barang pokok"},
    @{kanji="関税"; furigana="かんぜい"; arti="bea masuk cukai tarif kepabeanan komoditas impor"},
    @{kanji="通関"; furigana="つうかん"; arti="pemeriksaan izin clearance kepabeanan ekspor impor"},
    @{kanji="為替"; furigana="かわせ"; arti="mekanisme valuta asing kurs pertukaran mata uang"},
    @{kanji="円高"; furigana="えんだか"; arti="apresiasi penguatan nilai tukar mata uang yen jepang"},
    @{kanji="円安"; furigana="えんやす"; arti="depresiasi pelemahan nilai tukar mata uang yen jepang"},
    @{kanji="インフレ"; furigana="いんふれ"; arti="inflasi kenaikan harga komoditas kebutuhan hidup"},
    @{kanji="デフレ"; furigana="でふれ"; arti="deflasi penurunan harga barang akibat kelesuan daya beli"},
    @{kanji="バブル"; furigana="ばぶる"; arti="gelembung lonjakan harga spekulasi aset membuncah"},
    @{kanji="暴落"; furigana="ぼうらく"; arti="anjlok terjun bebas kejatuhan harga saham di bursa"},
    @{kanji="急落"; furigana="きゅうらく"; arti="penurunan merosot tajam kurva indeks harga pasar"},
    @{kanji="暴騰"; furigana="ぼうとう"; arti="lonjakan meroket tajam harga komoditas pangan minyak"},
    @{kanji="急騰"; furigana="きゅうとう"; arti="terbang melambung tinggi grafik harga secara tiba-tiba"},
    @{kanji="下落"; furigana="げらく"; arti="penurunan penyusutan valuasi harga instrumen investasi"},
    @{kanji="横ばい"; furigana="よこばい"; arti="kondisi mendatar stabil tiada fluktuasi berarti"},
    @{kanji="高止まり"; furigana="たかどまり"; arti="bertengger di kisaran harga tinggi tiada kunjung turun"},
    @{kanji="底入れ"; furigana="そこいれ"; arti="menyentuh titik terendah dasar sebelum kembali bangkit"},
    @{kanji="反発"; furigana="はんぱつ"; arti="pantulan rebound kenaikan harga; resistensi perlawanan"},
    @{kanji="反落"; furigana="はんらく"; arti="koreksi kembali melemah pasca reli kenaikan sesaat"},
    @{kanji="乱高下"; furigana="らんこうげ"; arti="fluktuasi ekstrem liar naik turun tajam harga pasar"},
    @{kanji="相場"; furigana="そうば"; arti="pergerakan fluktuasi harga pasar komoditas perdagangan"},

    # Social Demography, Welfare & Civil Affairs
    @{kanji="少子化"; furigana="しょうしか"; arti="fenomena tren penurunan angka kelahiran bayi balita"},
    @{kanji="高齢化"; furigana="こうれいか"; arti="penuaan populasi pertambahan rasio penduduk lansia"},
    @{kanji="少子高齢化"; furigana="しょうしこうれいか"; arti="krisis penurunan kelahiran dibarengi lonjakan lansia"},
    @{kanji="過疎"; furigana="かそ"; arti="penurunan drastis populasi penduduk kawasan pedesaan"},
    @{kanji="過疎化"; furigana="かそか"; arti="proses pengosongan perkampungan ditinggal kaum muda"},
    @{kanji="過密"; furigana="かみつ"; arti="kepadatan sesak berlebih konsentrasi hunian kota"},
    @{kanji="一極集中"; furigana="いっきょくしゅうちゅう"; arti="sentralisasi tumpuan terpusat di satu kutub kota utama"},
    @{kanji="地方創生"; furigana="ちほうそうせい"; arti="revitalisasi kebangkitan pemberdayaan potensi daerah"},
    @{kanji="限界集落"; furigana="げんかいしゅうらく"; arti="desa terpencil mayoritas lansia di ambang kepunahan"},
    @{kanji="空き家"; furigana="あきや"; arti="rumah kosong telantar lapuk tanpa penghuni mukim"},
    @{kanji="待機児童"; furigana="たいきじどう"; arti="anak balita dalam daftar antrean penitipan anak"},
    @{kanji="介護"; furigana="かいご"; arti="pelayanan pendampingan perawatan lansia jompo"},
    @{kanji="介護士"; furigana="かいごし"; arti="pramurukti perawat ahli pendamping lansia bersertifikat"},
    @{kanji="保育"; furigana="ほいく"; arti="pengasuhan dan pembinaan tumbuh kembang anak balita"},
    @{kanji="保育士"; furigana="ほいくし"; arti="guru pendidik pengasuh profesional taman kanak-kanak"},
    @{kanji="福祉"; furigana="ふくし"; arti="kesejahteraan sosial kemakmuran taraf hidup rakyat"},
    @{kanji="社会保障"; furigana="しゃかいほしょう"; arti="sistem jejaring perlindungan jaminan sosial negara"},
    @{kanji="格差"; furigana="かくさ"; arti="kesenjangan disparitas ketimpangan ekonomi strata"},
    @{kanji="貧困"; furigana="ひんこん"; arti="kemiskinan hidup kekurangan sandang pangan papan"},
    @{kanji="貧富"; furigana="ひんぷ"; arti="disparitas jurang pemisah antara si kaya dan si miskin"},
    @{kanji="階層"; furigana="かいそう"; arti="lapisan tingkatan strata kelas sosial bermasyarakat"},
    @{kanji="階級"; furigana="かいきゅう"; arti="tingkatan kelas sosial pembeda kasta hierarki"},
    @{kanji="身分"; furigana="みぶん"; arti="status kedudukan sosial harkat martabat pergaulan"},
    @{kanji="世襲"; furigana="せしゅう"; arti="pewarisan suksesi turun-temurun kursi jabatan keluarga"},
    @{kanji="血統"; furigana="けっとう"; arti="garis kemurnian trah darah silsilah keluarga luhur"},
    @{kanji="家柄"; furigana="いえがら"; arti="bobot kehormatan silsilah nama besar marga keluarga"},
    @{kanji="縁談"; furigana="えんだん"; arti="lamaran penjodohan taaruf pernikahan adat kerabat"},
    @{kanji="仲人"; furigana="なこうど"; arti="mak comblang perantara juru sambung lamaran jodoh"},
    @{kanji="結納"; furigana="ゆいのう"; arti="serah terima hantaran seserahan peminangan resmi"},
    @{kanji="結納品"; furigana="ゆいのうひん"; arti="barang bingkisan hantaran seserahan pertunangan"},
    @{kanji="婚姻"; furigana="こんいん"; arti="ikatan janji suci pertalian perkawinan sah di mata hukum"},
    @{kanji="婚姻届"; furigana="こんいんとどけ"; arti="akta formulir pencatatan sipil perkawinan negara"},
    @{kanji="離婚"; furigana="りこん"; arti="pemutusan ikatan perceraian resmi suami dan istri"},
    @{kanji="離婚届"; furigana="りこんとどけ"; arti="akta formulir permohonan pendaftaran perceraian"},
    @{kanji="親権"; furigana="しんけん"; arti="hak asuh kekuasaan orang tua melindungi anak kandung"},
    @{kanji="監護"; furigana="かんご"; arti="pengawasan perawatan pemeliharaan jasmani anak asuh"},
    @{kanji="後見"; furigana="こうけん"; arti="perwalian perlindungan hukum atas kepentingan anak yatim"},
    @{kanji="後見人"; furigana="こうけんにん"; arti="wali pengampu penjamin kepentingan hukum anak yatim"},
    @{kanji="遺言"; furigana="ゆいごん"; arti="surat wasiat pesan amanah sebelum menghembuskan nafas"},
    @{kanji="遺産"; furigana="いさん"; arti="harta pusaka warisan peninggalan orang tua leluhur"},
    @{kanji="相続"; furigana="そうぞく"; arti="proses pengalihan peralihan hak waris harta pusaka"},
    @{kanji="相続税"; furigana="そうぞくぜい"; arti="pajak penghasilan atas penerimaan warisan pusaka"},
    @{kanji="遺族"; furigana="いぞく"; arti="anggota keluarga duka sanak famili yang ditinggalkan"},
    @{kanji="遺品"; furigana="いひん"; arti="barang-barang peninggalan kenangan almarhum terkasih"},
    @{kanji="形見"; furigana="かたみ"; arti="barang cenderamata kenang-kenangan dari mendiang"},

    # Sensory Actions, Verbs, Craft & Scenery
    @{kanji="潤う"; furigana="うるおう"; arti="menjadi lembap basah segar; makmur sejahtera keuangan"},
    @{kanji="潤す"; furigana="うるおす"; arti="melembapkan tenggorokan dahaga; memakmurkan ekonomi"},
    @{kanji="澄む"; furigana="すむ"; arti="jernih bening air telaga; jernih merdu artikulasi suara"},
    @{kanji="濁る"; furigana="にごる"; arti="keruh kotor air sungai banjir; parau serak suara"},
    @{kanji="澄ます"; furigana="すます"; arti="memasang telinga menyimak saksama; bersikap sok jaim"},
    @{kanji="耳を澄ます"; furigana="みみをすます"; arti="memasang telinga mendengarkan secara saksama"},
    @{kanji="尖る"; furigana="とがる"; arti="meruncing lancip ujung pena; sensitif tegang saraf emosi"},
    @{kanji="尖らす"; furigana="とがらす"; arti="memonyongkan bibir cemberut; meruncingkan mata pensil"},
    @{kanji="鈍る"; furigana="にぶる"; arti="tumpul mata pisau dapur; menurun tumpul ketajaman nalar"},
    @{kanji="鈍感"; furigana="どんかん"; arti="tidak peka lambat tanggap tebal perasaan bebal"},
    @{kanji="敏感"; furigana="びんかん"; arti="peka sensitif lekas bereaksi pada rangsangan luar"},
    @{kanji="鈍化"; furigana="どんか"; arti="perlambatan laju penurunan kecepatan pertumbuhan"},
    @{kanji="鋭敏"; furigana="えいびん"; arti="tajam tangkas peka daya pengamatan insting"},
    @{kanji="機敏"; furigana="きびん"; arti="tangkas gesit cekatan refleks gerak koordinasi"},
    @{kanji="緩慢"; furigana="かんまん"; arti="lamban santai lambat pergerakan laju birokrasi"},
    @{kanji="散漫"; furigana="さんまん"; arti="buyar buyar tidak terarah konsentrasi fokus pikiran"},
    @{kanji="茫然"; furigana="ぼうぜん"; arti="tertegun terperangah bengong linglung kalut sanubari"},
    @{kanji="呆然"; furigana="ぼうぜん"; arti="terpana kaget ternganga tiada bersuara kata"},
    @{kanji="俄然"; furigana="がぜん"; arti="mendadak seketika itu juga berubah memanas atmosfer"},
    @{kanji="突如"; furigana="とつじょ"; arti="mendadak tiba-tiba muncul tanpa ada tanda aba-aba"},
    @{kanji="不意に"; furigana="ふいに"; arti="tiba-tiba tanpa disangka datang menyapa mengejutkan"},
    @{kanji="唐突"; furigana="とうとつ"; arti="mendadak janggal mengejutkan tanpa permisi awal"},
    @{kanji="翻す"; furigana="ひるがえす"; arti="mengibarkan bendera; membalikkan pendirian sikap"},
    @{kanji="翻る"; furigana="ひるがえる"; arti="berkibar melambai ditiup angin sepoi di puncak tiang"},
    @{kanji="覆す"; furigana="くつがえす"; arti="menggulingkan rezim; membatalkan putusan vonis hakim"},
    @{kanji="覆る"; furigana="くつがえる"; arti="terbalik terbalik kapal perahu; runtuh tatanan lama"},
    @{kanji="揺るがす"; furigana="ゆるがす"; arti="mengguncang menggetarkan pilar stabilitas tatanan negeri"},
    @{kanji="揺らぐ"; furigana="ゆらぐ"; arti="bergoyang goyah keyakinan pendirian dalam sanubari"},
    @{kanji="揺らめく"; furigana="ゆらめく"; arti="bergoyang meliuk-liuk lidah api lilin di kegelapan"},
    @{kanji="揺さぶる"; furigana="ゆさぶる"; arti="mengguncang-guncangkan bahu; menggetarkan emosi kalbu"},
    @{kanji="震わせる"; furigana="ふるわせる"; arti="menggetarkan suara gemetar menahan tangis duka"},
    @{kanji="身震い"; furigana="みぶるい"; arti="bergidik menggigil gemetar seluruh sekujur raga"},
    @{kanji="鳥肌"; furigana="とりはだ"; arti="merinding bulu kuduk berdiri akibat takjub dingin"},
    @{kanji="奮い立つ"; furigana="ふるいたつ"; arti="bangkit bersemangat menggelora tekad juang kalbu"},
    @{kanji="立ち向かう"; furigana="たちむかう"; arti="maju menghadapi lawan menantang rintangan badai"},
    @{kanji="立ち遅れる"; furigana="たちおくれる"; arti="tertinggal di belakang kompetisi kemajuan zaman"},
    @{kanji="立ち替わる"; furigana="たちかわる"; arti="silih berganti bergantian datang berkunjung silih"},
    @{kanji="入れ替える"; furigana="いれかえる"; arti="menukar mengganti posisi susunan perabot ruang"},
    @{kanji="差し替える"; furigana="さしかえる"; arti="mengganti menukar lembaran halaman draf dokumen"},
    @{kanji="駆け抜ける"; furigana="かけぬける"; arti="berlari kencang menerobos lorong lintasan waktu"},
    @{kanji="潜り抜ける"; furigana="くぐりぬける"; arti="berhasil menyelinap lolos dari jaring rintangan"},
    @{kanji="すり抜ける"; furigana="すりぬける"; arti="meloloskan diri licin dari kepungan barikade"},
    @{kanji="掻い潜る"; furigana="かいくぐる"; arti="menerobos celah pengawasan aparat penjaga malam"},
    @{kanji="掻き乱す"; furigana="かきみだす"; arti="mengacak-acak mengaduk-aduk ketenteraman suasana damai"},
    @{kanji="掻き消す"; furigana="かきけす"; arti="menelan menenggelamkan lenyap suara gemuruh petir"},
    @{kanji="掻き集める"; furigana="かきあつめる"; arti="mengumpulkan meraup serpihan koin keping bertebaran"},
    @{kanji="寄せ集める"; furigana="よせあつめる"; arti="mengumpulkan menghimpun aneka ragam barang bekas"},
    @{kanji="かき回す"; furigana="かきまわす"; arti="mengaduk cairan panci; mengacaukan keheningan tim"},
    @{kanji="振り回す"; furigana="ふりまわす"; arti="mengayunkan pedang; mempermainkan perasaan batin"},
    @{kanji="乗り回す"; furigana="のりまわす"; arti="mengendarai melajukan mobil keliling pusat kota"},
    @{kanji="逃げ回る"; furigana="にげまわる"; arti="berlari ke sana kemari kabur menghindar tangkapan"},
    @{kanji="探し回る"; furigana="さがしまわる"; arti="berkeliling mencari ke mana-mana barang yang raib"},
    @{kanji="駆け回る"; furigana="かけまわる"; arti="berlarian kian kemari mengitari padang rumput"},
    @{kanji="飛び交う"; furigana="とびかう"; arti="berseliweran terbang melintas di langit; kabar hoaks"},
    @{kanji="行き交う"; furigana="ゆきかう"; arti="lalu-lalang berseliweran pejalan kaki di trotoar"},
    @{kanji="分かち合う"; furigana="わかちあう"; arti="saling berbagi rasa duka lara dan suka cita bersama"},
    @{kanji="語り合う"; furigana="かたりあう"; arti="saling mencurahkan isi hati bertukar kisah masa lalu"},
    @{kanji="認め合う"; furigana="みとめあう"; arti="saling mengakui menghargai kelebihan potensi rekan"},
    @{kanji="信じ合う"; furigana="しんじあう"; arti="saling menaruh kepercayaan teguh ikatan sahabat"},
    @{kanji="称え合う"; furigana="たたえあう"; arti="saling melontarkan pujian apresiasi prestasi kawan"},
    @{kanji="持ちつ持たれつ"; furigana="もちつもたれつ"; arti="saling bergantung saling membutuhkan tolong-menolong"},
    @{kanji="試みる"; furigana="こころみる"; arti="mencoba berikhtiar melakukan eksperimen perdana"},
    @{kanji="企図する"; furigana="きとする"; arti="merencanakan memprakarsai proyek strategis terpadu"},
    @{kanji="遂げる"; furigana="とげる"; arti="menuntaskan meraih keberhasilan cita-cita mulia"},
    @{kanji="成し遂げる"; furigana="なしとげる"; arti="menuntaskan perjuangan akbar hingga garis akhir"},
    @{kanji="遣り遂げる"; furigana="やりとげる"; arti="menyelesaikan mandat tugas hingga tuntas paripurna"},
    @{kanji="やり切る"; furigana="やりきる"; arti="berjuang sekuat tenaga hingga tetes keringat akhir"},
    @{kanji="尽きる"; furigana="つきる"; arti="habis tandas terkuras seluruh daya tenaga energi"},
    @{kanji="尽くす"; furigana="つくす"; arti="mengerahkan segenap daya mengabdi sepenuh jiwa raga"},
    @{kanji="尽力する"; furigana="じんりょくする"; arti="berikhtiar sekuat tenaga mencurahkan dedikasi bakti"},
    @{kanji="最善を尽くす"; furigana="さいぜんをつくす"; arti="berikhtiar memberikan yang terbaik seoptimal mungkin"},
    @{kanji="捧げる"; furigana="ささげる"; arti="mempersembahkan membaktikan jiwa raga demi nusa"},
    @{kanji="献身"; furigana="けんしん"; arti="pengorbanan dedikasi tulus jiwa raga demi sesama"},
    @{kanji="献身的な"; furigana="けんしんてきな"; arti="berjiwa pengorbanan luhur tanpa pamrih pribadi"},
    @{kanji="奉仕"; furigana="ほうし"; arti="pelayanan bakti sosial sukarela tanpa imbalan jasa"},
    @{kanji="恵む"; furigana="めぐむ"; arti="mengasihi memberi sedekah santunan pada yang lemah"},
    @{kanji="恵み"; furigana="めぐみ"; arti="berkah karunia limpahan rahmat anugerah illahi"},
    @{kanji="潤沢"; furigana="じゅんたく"; arti="melimpah ruah berlimpah cadangan dana logistik kas"},
    @{kanji="豊潤"; furigana="ほうじゅん"; arti="ranum subur melimpah cita rasa sari buah manis"},
    @{kanji="肥沃"; furigana="ひよく"; arti="subur makmur gembur tanah humus lahan pertanian"},
    @{kanji="不毛"; furigana="ふもう"; arti="tandus gersang tiada menghasilkan karya manfaat"},
    @{kanji="荒涼"; furigana="こうりょう"; arti="gersang sunyi senyap membentang gurun pasir luas"},
    @{kanji="殺風景"; furigana="さっぷうけい"; arti="hambar monoton tiada pemandangan indah gersang kamar"},
    @{kanji="閑静"; furigana="かんせい"; arti="tenang damai asri sunyi kawasan hunian mukim"},
    @{kanji="閑散"; furigana="かんさん"; arti="sepi lengang melompong tiada pengunjung pusat belanja"},
    @{kanji="繁華"; furigana="はんか"; arti="ramai gemerlap sibuk perniagaan jalan raya kota"},
    @{kanji="繁華街"; furigana="はんかがい"; arti="kawasan pusat perbelanjaan hiburan gemerlap riuh"},
    @{kanji="歓楽街"; furigana="かんらくがい"; arti="kawasan distrik hiburan malam gemerlap lampu warna"},
    @{kanji="密集"; furigana="みっしゅう"; arti="berdesak-desakan berhimpitan padat pemukiman sempit"},
    @{kanji="点在"; furigana="てんざい"; arti="tersebar berserakan terpencar di berbagai titik lokasi"},
    @{kanji="散在"; furigana="さんざい"; arti="berserakan tersebar titik-titik pulau kecil di laut"},
    @{kanji="散乱"; furigana="さんらん"; arti="berantakan berceceran puing barang pasca gempa bumi"},
    @{kanji="散策"; furigana="さんさく"; arti="berjalan-jalan santai menikmati asrinya taman bunga"},

    # Crafts, Architecture, Foundations & Core Essentials
    @{kanji="漂白"; furigana="ひょうはく"; arti="pemutihan penghilangan noda serat kain klorin"},
    @{kanji="漂白剤"; furigana="ひょうはくざい"; arti="cairan bahan pemutih pakaian klorin antiseptik"},
    @{kanji="研磨"; furigana="けんま"; arti="pengasahan penggosokan pemolesan batu permata"},
    @{kanji="研磨剤"; furigana="けんまざい"; arti="pasta bubuk abrasif penghalus polesan logam"},
    @{kanji="彫刻"; furigana="ちょうこく"; arti="seni ukir pahat patung relief bebatuan marmer"},
    @{kanji="陶芸"; furigana="とうげい"; arti="seni kriya keramik tembikar tanah liat bakar"},
    @{kanji="漆器"; furigana="しっき"; arti="seni pernis lak kayu mangkuk tradisional jepang"},
    @{kanji="染織"; furigana="せんしょく"; arti="seni kriya tenun dan celup pewarnaan kain tekstil"},
    @{kanji="織物"; furigana="おりもの"; arti="kain tenunan bermotif indah corak tradisional"},
    @{kanji="紡績"; furigana="ぼうせき"; arti="pemintalan serat kapas menjadi benang tekstil"},
    @{kanji="裁縫"; furigana="さいほう"; arti="keterampilan menjahit jarum benang pakaian rumah"},
    @{kanji="縫製"; furigana="ほうせい"; arti="penjahitan perakitan pakaian jadi garmen pabrik"},
    @{kanji="補修"; furigana="ほしゅう"; arti="penambalan perbaikan retakan dinding jalan aspal"},
    @{kanji="修繕"; furigana="しゅうぜん"; arti="reparasi pembetulan perkakas mebel rumah tangga"},
    @{kanji="改修"; furigana="かいしゅう"; arti="pemugaran peremajaan fasilitas dermaga pelabuhan"},
    @{kanji="増築"; furigana="ぞうちく"; arti="perluasan penambahan luas ruangan paviliun rumah"},
    @{kanji="改築"; furigana="かいちく"; arti="pembangunan ulang renovasi arsitektur gedung lama"},
    @{kanji="解体"; furigana="かいたい"; arti="pembongkaran peruntuhan rangka gedung tua eskavator"},
    @{kanji="築く"; furigana="きずく"; arti="membangun membina benteng kokoh; merajut relasi"},
    @{kanji="礎"; furigana="いしずえ"; arti="batu fondasi tumpuan peradaban kejayaan nusa"},
    @{kanji="礎石"; furigana="そせき"; arti="batu penjuru penopang utama sudut konstruksi"},
    @{kanji="骨組み"; furigana="ほねぐみ"; arti="kerangka struktur tiang balok penopang atap"},
    @{kanji="骨格"; furigana="こっかく"; arti="kerangka susunan tulang; draf rancangan konsep"},
    @{kanji="土台"; furigana="どだい"; arti="fondasi alas pijakan tumpuan utama bangunan"},
    @{kanji="根底"; furigana="こんてい"; arti="dasar tumpuan terdalam filosofi cara pandang"},
    @{kanji="根本"; furigana="こんぽん"; arti="pangkal pokok muasal akar terdalam permasalahan"},
    @{kanji="根本的"; furigana="こんぽんてき"; arti="secara mendasar fundamental menyeluruh tuntas"},
    @{kanji="根源"; furigana="こんげん"; arti="mata air hulu pangkal muasal sumber kehidupan"},
    @{kanji="根幹"; furigana="こんかん"; arti="batang pilar inti penopang keutuhan sistem"},
    @{kanji="枢要"; furigana="すうよう"; arti="poros peran sentral amat penting bagi stabilitas"},
    @{kanji="中枢"; furigana="ちゅうすう"; arti="pusat komando saraf pengendali operasi armada"},
    @{kanji="中核"; furigana="ちゅうかく"; arti="inti nukleus garda terdepan penggerak perubahan"},
    @{kanji="大綱"; furigana="たいこう"; arti="garis-garis besar pokok pedoman arah kebijakan"},
    @{kanji="要綱"; furigana="ようこう"; arti="petunjuk teknis juknis panduan operasional SOP"}
)

$cleanBatch5 = [System.Collections.Generic.List[object]]::new()
$seenBatch5Kanji = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

foreach ($c in $candidatePool5) {
    $k = $c.kanji.Trim()
    if (-not $existingKanjiSet.Contains($k) -and -not $seenBatch5Kanji.Contains($k)) {
        $cleanBatch5.Add($c)
        $seenBatch5Kanji.Add($k) | Out-Null
    }
}

Write-Host "Filtered clean candidates in candidatePool5: $($cleanBatch5.Count)"
