[Console]::OutputEncoding = [System.Text.Encoding]::UTF8

$existingJsonRaw = Get-Content -Raw -Encoding UTF8 './data/vocabulary.json'
$existing = $existingJsonRaw | ConvertFrom-Json
Write-Host "Current total existing words in database: $($existing.Length)"

$existingKanjiSet = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)
foreach ($item in $existing) {
    if ($item.kanji) {
        $existingKanjiSet.Add($item.kanji.Trim()) | Out-Null
    }
}

$candidatePool = @(
    # Politics, Law & Administration
    @{kanji="憲法"; furigana="けんぽう"; arti="konstitusi; undang-undang dasar negara"},
    @{kanji="条約"; furigana="じょうやく"; arti="traktat; perjanjian diplomatik internasional"},
    @{kanji="採決"; furigana="さいけつ"; arti="pemungutan suara; voting penentuan keputusan"},
    @{kanji="審議"; furigana="しんぎ"; arti="pertimbangan sidang telaah rancangan keputusan"},
    @{kanji="議案"; furigana="ぎあん"; arti="draf rancangan agenda undang-undang"},
    @{kanji="議会"; furigana="ぎかい"; arti="parlemen; majelis dewan perwakilan rakyat"},
    @{kanji="政策"; furigana="せいさく"; arti="kebijakan politik strategis kenegaraan"},
    @{kanji="施策"; furigana="しさく"; arti="langkah operasional pelaksanaan kebijakan"},
    @{kanji="司法"; furigana="しほう"; arti="kekuasaan kehakiman yudikatif pengadilan"},
    @{kanji="立法"; furigana="りっぽう"; arti="pembuatan peraturan legislatif parlemen"},
    @{kanji="行政"; furigana="ぎょうせい"; arti="administrasi pemerintahan birokrasi eksekutif"},
    @{kanji="判決"; furigana="はんけつ"; arti="putusan vonis hakim di pengadilan"},
    @{kanji="裁判"; furigana="さいばん"; arti="persidangan perkara di hadapan pengadilan"},
    @{kanji="告訴"; furigana="こくそ"; arti="pengaduan tuntutan perkara pidana hukum"},
    @{kanji="訴訟"; furigana="そしょう"; arti="proses litigasi gugatan sengketa hukum"},
    @{kanji="陪審"; furigana="ばいしん"; arti="dewan juri persidangan warga independen"},
    @{kanji="証拠"; furigana="しょうこ"; arti="alat bukti eviden kebenaran perkara hukum"},
    @{kanji="容疑"; furigana="ようぎ"; arti="sangkaan tuduhan kecurigaan tindak pidana"},
    @{kanji="容疑者"; furigana="ようぎしゃ"; arti="tersangka terduga pelaku tindak pidana"},
    @{kanji="懲役"; furigana="ちょうえき"; arti="pidana penjara kurungan dengan kerja paksa"},
    @{kanji="執行"; furigana="しっこう"; arti="eksekusi pelaksanaan surat putusan hukum"},
    @{kanji="拘束"; furigana="こうそく"; arti="penahanan restriksi fisik; pembatasan gerak"},
    @{kanji="釈放"; furigana="しゃくほう"; arti="pelepasan pembebasan tahanan dari kurungan"},
    @{kanji="治安"; furigana="ちあん"; arti="ketertiban dan keamanan publik masyarakat"},
    @{kanji="秩序"; furigana="ちつじょ"; arti="keteraturan tatanan norma tatanan sosial"},
    @{kanji="暴動"; furigana="ぼうどう"; arti="huru-hara kerusuhan massal anarki"},
    @{kanji="紛争"; furigana="ふんそう"; arti="sengketa konflik perselisihan antar pihak"},
    @{kanji="停戦"; furigana="ていせん"; arti="gencatan senjata penghentian kontak tembak"},
    @{kanji="和睦"; furigana="わぼく"; arti="perjanjian damai rekonsiliasi persahabatan"},
    @{kanji="条項"; furigana="じょうこう"; arti="butir pasal klausul kontrak perjanjian"},
    @{kanji="規定"; furigana="きてい"; arti="ketentuan regulasi formal undang-undang"},
    @{kanji="規約"; furigana="きやく"; arti="anggaran dasar tata tertib keanggotaan"},
    @{kanji="準拠"; furigana="じゅんきょ"; arti="kepatuhan berlandaskan standar baku acuan"},
    @{kanji="規範"; furigana="きはん"; arti="norma patokan acuan etika moralitas"},
    @{kanji="慣習"; furigana="かんしゅう"; arti="adat istiadat kelaziman tradisi leluhur"},
    @{kanji="慣行"; furigana="かんこう"; arti="praktik rutinitas kerja yang lazim berjalan"},
    @{kanji="先例"; furigana="せんれい"; arti="preseden rujukan peristiwa masa lampau"},
    @{kanji="前例"; furigana="ぜんれい"; arti="contoh kasus serupa terdahulu di masa lalu"},
    @{kanji="風潮"; furigana="ふうちょう"; arti="tren kecenderungan arus pemikiran zaman"},
    @{kanji="世論"; furigana="せろん"; arti="opini publik aspirasi suara khalayak ramai"},
    @{kanji="住民"; furigana="じゅうみん"; arti="penduduk warga setempat mukim domisili"},
    @{kanji="戸籍"; furigana="こせき"; arti="buku catatan sipil registrasi keluarga"},
    @{kanji="印鑑"; furigana="いんかん"; arti="cap stempel segel nama resmi legal"},
    @{kanji="捺印"; furigana="なついん"; arti="pembubuhan cap stempel pada lembar akta"},
    @{kanji="署名"; furigana="しょめい"; arti="tanda tangan pembubuhan paraf dokumen"},
    @{kanji="領収書"; furigana="りょうしゅうしょ"; arti="kuitansi tanda terima pelunasan sah"},
    @{kanji="明細書"; furigana="めいさいしょ"; arti="surat lembar rincian kalkulasi perincian"},
    @{kanji="請求書"; furigana="せいきゅうしょ"; arti="lembar invoice tagihan pelunasan biaya"},
    @{kanji="見積書"; furigana="みつもりしょ"; arti="lembar estimasi penawaran anggaran proyek"},
    @{kanji="納品書"; furigana="のうひんしょ"; arti="surat jalan bukti serah terima pesanan"},
    @{kanji="保証書"; furigana="ほしょうしょ"; arti="surat kartu garansi reparasi pabrikan"},
    @{kanji="推薦状"; furigana="すいせんじょう"; arti="surat rekomendasi kapabilitas akademik/kerja"},
    @{kanji="履歴書"; furigana="りれきしょ"; arti="daftar riwayat hidup kurikulum vitae CV"},
    @{kanji="職務"; furigana="しょくむ"; arti="beban tugas pokok kewajiban jabatan"},
    @{kanji="兼業"; furigana="けんぎょう"; arti="pekerjaan sampingan merangkap usaha lain"},
    @{kanji="副業"; furigana="ふくぎょう"; arti="usaha sambilan sampingan penambah rezeki"},
    @{kanji="本業"; furigana="ほんぎょう"; arti="profesi pekerjaan pencaharian utama"},
    @{kanji="定年"; furigana="ていねん"; arti="batas usia batas pensiun wajib karyawan"},
    @{kanji="勤続"; furigana="きんぞく"; arti="masa bakti kerja bertahun-tahun di kantor"},
    @{kanji="退職金"; furigana="たいしょくきん"; arti="uang pesangon tunjangan pensiun karyawan"},
    @{kanji="年金"; furigana="ねんきん"; arti="dana pensiun jaminan tunjangan hari tua"},
    @{kanji="保険"; furigana="ほけん"; arti="asuransi jaminan proteksi risiko finansial"},
    @{kanji="保険証"; furigana="ほけんしょう"; arti="kartu kepesertaan jaminan asuransi kesehatan"},

    # Medical, Health & Biology
    @{kanji="診察"; furigana="しんさつ"; arti="pemeriksaan klinis fisik oleh dokter"},
    @{kanji="診療"; furigana="しんりょう"; arti="pelayanan tindakan konsultasi dan terapi medis"},
    @{kanji="処方"; furigana="しょほう"; arti="peresepan takaran obat oleh dokter ahli"},
    @{kanji="処方箋"; furigana="しょほうせん"; arti="lembar resep obat dokter untuk ditebus di apotek"},
    @{kanji="副作用"; furigana="ふくさよう"; arti="efek samping reaksi obat yang tak diharapkan"},
    @{kanji="効能"; furigana="こうのう"; arti="khasiat keampuhan formula obat/herbal"},
    @{kanji="免疫"; furigana="めんえき"; arti="sistem imun daya tahan kekebalan tubuh"},
    @{kanji="感染"; furigana="かんせん"; arti="infeksi transmisi kuman bibit penyakit"},
    @{kanji="伝染"; furigana="でんせん"; arti="penularan wabah epidemi secara meluas"},
    @{kanji="隔離"; furigana="かくり"; arti="tindakan isolasi karantina pasien menular"},
    @{kanji="潜伏"; furigana="せんぷく"; arti="masa inkubasi kuman bersembunyi di tubuh"},
    @{kanji="発症"; furigana="はっしょう"; arti="kemunculan gejala klinis pertama penyakit"},
    @{kanji="重症"; furigana="じゅうしょう"; arti="kondisi sakit kritis parah stadium tinggi"},
    @{kanji="軽症"; furigana="けいしょう"; arti="gejala penyakit taraf enteng ringan"},
    @{kanji="慢性"; furigana="まんせい"; arti="penyakit menahun kronis kambuhan berkala"},
    @{kanji="急性"; furigana="きゅうせい"; arti="gangguan kesehatan datang mendadak akut"},
    @{kanji="後遺症"; furigana="こういしょう"; arti="dampak komplikasi sisa pasca kesembuhan"},
    @{kanji="完治"; furigana="かんち"; arti="kesembuhan total paripurna tanpa sisa penyakit"},
    @{kanji="リハビリ"; furigana="りはびり"; arti="terapi pemulihan rehabilitasi fungsi organ"},
    @{kanji="診断"; furigana="しんだん"; arti="penegakan vonis diagnosis medis penyakit"},
    @{kanji="問診"; furigana="もんしん"; arti="anamnesis tanya jawab riwayat keluhan pasien"},
    @{kanji="点滴"; furigana="てんてき"; arti="pemberian infus cairan nutrisi lewat vena"},
    @{kanji="麻酔"; furigana="ますい"; arti="pembiusan anestesi sebelum tindakan bedah"},
    @{kanji="消毒"; furigana="しょうどく"; arti="desinfeksi sterilisasi pembersihan luka antiseptik"},
    @{kanji="包帯"; furigana="ほうたい"; arti="kain perban pembalut balutan luka patah"},
    @{kanji="絆創膏"; furigana="ばんそうこう"; arti="plester pembalut steril perekat luka kecil"},
    @{kanji="救急"; furigana="きゅうきゅう"; arti="layanan gawat darurat kilat unit rumah sakit"},
    @{kanji="応急手当"; furigana="おうきゅうてあて"; arti="tindakan pertolongan pertama pada kecelakaan"},
    @{kanji="人工呼吸"; furigana="じんこうこきゅう"; arti="pernapasan buatan resusitasi darurat napas"},
    @{kanji="心臓麻痺"; furigana="しんぞうまひ"; arti="serangan henti jantung mendadak fatal"},
    @{kanji="脳卒中"; furigana="のうそっちゅう"; arti="serangan stroke penyumbatan pembuluh darah otak"},
    @{kanji="高血圧"; furigana="こうけつあつ"; arti="tekanan darah tinggi kondisi hipertensi"},
    @{kanji="糖尿病"; furigana="とうにょうびょう"; arti="penyakit gula kencing manis diabetes melitus"},
    @{kanji="アレルギー"; furigana="あれるぎー"; arti="hipersensitivitas alergi terhadap zat pemicu"},
    @{kanji="花粉症"; furigana="かふんしょう"; arti="alergi rinitis akibat serbuk sari tanaman"},

    # N2 Corporate, Management & Organization Verbs
    @{kanji="補佐する"; furigana="ほさする"; arti="mendampingi membantu tugas kepemimpinan atasan"},
    @{kanji="統括する"; furigana="とうかつする"; arti="mengepalai mengoordinasi divisi secara menyeluruh"},
    @{kanji="指揮する"; furigana="しきする"; arti="mengomando memimpin arahan regu/orkestra"},
    @{kanji="監督する"; furigana="かんとくする"; arti="mensupervisi mengawasi tata tertib jalannya proyek"},
    @{kanji="監査する"; furigana="かんさする"; arti="mengaudit memeriksa akuntabilitas pembukuan kas"},
    @{kanji="審査する"; furigana="しんさする"; arti="menyeleksi menelaah kelayakan portofolio pelamar"},
    @{kanji="査定する"; furigana="さていする"; arti="menilai menaksir valuasi harga wajar aset"},
    @{kanji="鑑定する"; furigana="かんていする"; arti="menilai orisinalitas keaslian karya seni antik"},
    @{kanji="考案する"; furigana="こうあんする"; arti="merancang menciptakan desain inovasi orisinal"},
    @{kanji="発案する"; furigana="はつあんする"; arti="mencetuskan ide usulan pertama di forum"},
    @{kanji="起案する"; furigana="きあんする"; arti="menyusun draf rancangan surat edaran keputusan"},
    @{kanji="発起する"; furigana="ほっきする"; arti="memprakarsai inisiasi gerakan pendirian yayasan"},
    @{kanji="設立する"; furigana="せつりつする"; arti="mendirikan mengesahkan pendirian badan hukum"},
    @{kanji="創立する"; furigana="そうりつする"; arti="mendirikan merintis tonggak lahirnya universitas"},
    @{kanji="創業する"; furigana="そうぎょうする"; arti="memulai merintis bisnis usaha wirausaha mandiri"},
    @{kanji="開業する"; furigana="かいぎょうする"; arti="membuka memulai operasional klinik/toko baru"},
    @{kanji="廃業する"; furigana="はいぎょうする"; arti="gulung tikar menghentikan operasional bisnis"},
    @{kanji="撤退する"; furigana="てったいする"; arti="menarik diri mundur dari pasar persaingan luar"},
    @{kanji="縮小する"; furigana="しゅくしょうする"; arti="memangkas mengecilkan skala operasional defisit"},
    @{kanji="拡大する"; furigana="かくだいする"; arti="memperbesar memperluas skala perniagaan cabang"},
    @{kanji="拡張する"; furigana="かくちょうする"; arti="memperluas daya tampung kapasitas memori server"},
    @{kanji="拡充する"; furigana="かくじゅうする"; arti="memperkaya melengkapi sarana fasilitas publik"},
    @{kanji="充実する"; furigana="じゅうじつする"; arti="sarat berbobot penuh makna pengalaman hidup"},
    @{kanji="補強する"; furigana="ほきょうする"; arti="memperkokoh menambal pilar konstruksi rentan"},
    @{kanji="強化する"; furigana="きょうかする"; arti="menggembleng memperkuat sistem benteng pertahanan"},
    @{kanji="妨害する"; furigana="ぼうがいする"; arti="mensabotase mengganggu stabilitas kelancaran"},
    @{kanji="阻止する"; furigana="そしする"; arti="menghadang menggagalkan upaya kejahatan musuh"},
    @{kanji="阻む"; furigana="はばむ"; arti="merintangi menghalangi jalan pencapaian mimpi"},
    @{kanji="遮断する"; furigana="しゃだんする"; arti="memutus memblokir jalur suplai listrik/air bersih"},
    @{kanji="密閉する"; furigana="みっぺいする"; arti="mengunci menyegel rapat wadah kedap udara"},
    @{kanji="密封する"; furigana="みっぷうする"; arti="menyegel mengepres kemasan steril makanan"},
    @{kanji="凝縮する"; furigana="ぎょうしゅくする"; arti="memadatkan mengentalkan intisari makna falsafah"},
    @{kanji="濃縮する"; furigana="のうしゅくする"; arti="memekatkan mengekstrak konsentrat sari buah"},
    @{kanji="希釈する"; furigana="きしゃくする"; arti="mengencerkan melarutkan zat kimia berkonsentrasi"},
    @{kanji="溶解する"; furigana="ようかいする"; arti="melebur mencairkan bongkahan logam padat"},
    @{kanji="分解する"; furigana="ぶんかいする"; arti="membongkar mengurai bagian onderdil komponen"},
    @{kanji="合成する"; furigana="ごうせいする"; arti="mensintesis meramu racikan bahan senyawa kimia"},
    @{kanji="融合する"; furigana="ゆうごうする"; arti="melebur menyatu secara harmonis beda elemen"},
    @{kanji="結合する"; furigana="けつごうする"; arti="mengikat menautkan ikatan rantai molekul atom"},
    @{kanji="連結する"; furigana="れんけつする"; arti="merangkaikan menggandengkan deretan gerbong"},
    @{kanji="連動する"; furigana="れんどうする"; arti="bergerak terhubung beriringan saling memicu"},
    @{kanji="併催する"; furigana="へいさいする"; arti="menyelenggarakan dua agenda akbar bersamaan"},
    @{kanji="併用する"; furigana="へいようする"; arti="mengkombinasikan menggunakan dua terapi berbarengan"},
    @{kanji="兼用する"; furigana="けんようする"; arti="multifungsi merangkap dua kegunaan praktis"},
    @{kanji="代用する"; furigana="だいようする"; arti="memanfaatkan bahan alternatif pengganti darurat"},
    @{kanji="補完する"; furigana="ほかんする"; arti="saling melengkapi mengisi rongga kekurangan data"},
    @{kanji="匹敵する"; furigana="ひってきする"; arti="sepadan mengimbangi ketangguhan sang juara"},
    @{kanji="凌駕する"; furigana="りょうがする"; arti="mengungguli melampaui jauh torehan masa lalu"},
    @{kanji="圧倒する"; furigana="あっとうする"; arti="melibas mendominasi telak superioritas lawan"},
    @{kanji="席巻する"; furigana="せっけんする"; arti="merajai menyapu bersih tren pasar komersial"},
    @{kanji="掌握する"; furigana="しょうあくする"; arti="menguasai memegang kendali tampuk otoritas"},
    @{kanji="統制する"; furigana="とうせいする"; arti="menertibkan mengontrol ketat regulasi pasar modal"},
    @{kanji="統治する"; furigana="とうちする"; arti="memerintah mengayomi rakyat segenap teritorial"},
    @{kanji="乱す"; furigana="みだす"; arti="merusak mengacaukan keharmonisan tatanan damai"},
    @{kanji="乱れる"; furigana="みだれる"; arti="menjadi buyar kacau berantakan tiada tertata"},
    @{kanji="崩れる"; furigana="くずれる"; arti="ambrol longsor runtuh tebing terjal diguyur hujan"},
    @{kanji="崩壊する"; furigana="ほうかいする"; arti="hancur lebur runtuh roboh stabilitas tatanan"},
    @{kanji="破裂する"; furigana="はれつする"; arti="meletus meledak pecah balon udara gas"},
    @{kanji="爆発する"; furigana="ばくはつする"; arti="meletup meledak dahsyat gunung vulkanik"},
    @{kanji="噴出する"; furigana="ふんしゅつする"; arti="menyembur keluar deras lava panas bumi"},
    @{kanji="噴火する"; furigana="ふんかする"; arti="mengeluarkan erupsi semburan awan panas vulkanik"},
    @{kanji="氾濫する"; furigana="はんらんする"; arti="meluap tumpah membanjiri dataran rendah"},
    @{kanji="浸水する"; furigana="しんすいする"; arti="tergenang kemasukan air bah banjir sungai"},
    @{kanji="水没する"; furigana="すいぼつする"; arti="karam tenggelam lenyap ke dasar perairan dalam"},
    @{kanji="漂流する"; furigana="ひょうりゅうする"; arti="terombang-ambing hanyut di samudera lepas"},
    @{kanji="漂う"; furigana="ただよう"; arti="melayang-layang di air; semerbak aroma harum"},
    @{kanji="放浪する"; furigana="ほうろうする"; arti="mengembara merantau tanpa destinasi tetap"},
    @{kanji="定住する"; furigana="ていじゅうする"; arti="menetap membangun hunian permanen di pedesaan"},
    @{kanji="移住する"; furigana="いじゅうする"; arti="bermigrasi pindah kependudukan ke luar pulau"},
    @{kanji="永住する"; furigana="えいじゅうする"; arti="bermukim tinggal seumur hidup di tanah rantau"},
    @{kanji="亡命する"; furigana="ぼうめいする"; arti="mencari perlindungan suaka politik ke luar negeri"},
    @{kanji="追放する"; furigana="ついほうする"; arti="mendeportasi mengusir pergi oknum pelanggar"},
    @{kanji="送還する"; furigana="そうかんする"; arti="memulangkan merepatriasi pengungsi ke tanah air"},
    @{kanji="収容する"; furigana="しゅうようする"; arti="menampung menyelamatkan pengungsi di balai kota"},

    # N2 Nuance Adjectives & Clarity
    @{kanji="顕著"; furigana="けんちょ"; arti="kentara nyata terlihat jelas mencolok perbedaannya"},
    @{kanji="明瞭"; furigana="めいりょう"; arti="gamblang terang benderang artikulasi bicaranya"},
    @{kanji="鮮明"; furigana="せんめい"; arti="jernih tajam kontras rekaman memori ingatan"},
    @{kanji="曖昧"; furigana="あいまい"; arti="kabur rancu ambigu membingungkan tafsirannya"},
    @{kanji="漠然"; furigana="ばくぜん"; arti="abstrak mengambang samar tanpa batas tegas"},
    @{kanji="明白"; furigana="めいはく"; arti="terang benderang jelas tiada terbantahkan"},
    @{kanji="歴然"; furigana="れきぜん"; arti="terpampang nyata kentara tanpa keraguan sedikit pun"},
    @{kanji="画一的"; furigana="かくいつてき"; arti="monoton seragam disamaratakan secara kaku"},
    @{kanji="多様"; furigana="たよう"; arti="majemuk beraneka ragam heterogen variatif jenisnya"},
    @{kanji="雑多"; furigana="ざった"; arti="rupa-rupa campur baur semrawut beraneka macam"},
    @{kanji="均一"; furigana="きんいつ"; arti="merata seragam setara mutu kualitas mutunya"},
    @{kanji="均等"; furigana="きんとう"; arti="terbagi sama rata proporsional porsi haknya"},
    @{kanji="奇妙"; furigana="きみょう"; arti="ganjil tak lazim aneh dipandang mata"},
    @{kanji="奇怪"; furigana="きかい"; arti="misterius aneh bin ajaib menggelikan akal"},
    @{kanji="巧妙"; furigana="こうみょう"; arti="cerdik piawai lihai skenario strategi taktiknya"},
    @{kanji="巧み"; furigana="たくみ"; arti="terampil piawai sentuhan tangan seniman ulung"},
    @{kanji="拙い"; furigana="つたない"; arti="canggung kaku belum lihai goresan karyanya"},
    @{kanji="粗末"; furigana="そまつ"; arti="ala kadarnya sederhana bersahaja; menyepelekan"},
    @{kanji="簡素"; furigana="かんそ"; arti="minimalis sederhana tanpa hiasan berlebihan"},
    @{kanji="素朴"; furigana="そぼく"; arti="polos bersahaja murni alami tanpa rekayasa"},
    @{kanji="緻密"; furigana="ちみつ"; arti="presisi sangat teliti cermat mendalam perhitungannya"},
    @{kanji="密接"; furigana="みっせつ"; arti="berpaut sangat erat bertaut kuat jalinan hubungannya"},
    @{kanji="親密"; furigana="しんみつ"; arti="intim hangat akrab persahabatan tali silaturahmi"},
    @{kanji="緊密"; furigana="きんみつ"; arti="koordinasi rapat sinergis antar satuan gugus tugas"},
    @{kanji="厳重"; furigana="げんじゅう"; arti="ketat berlapis pengawasan penjagaan perimeter"},
    @{kanji="頑健"; furigana="がんけん"; arti="berbadan kekar sehat bugar tangguh banting"},
    @{kanji="寛大"; furigana="かんだい"; arti="berlapang dada pemurah pemaaf kekhilafan insan"},
    @{kanji="謙遜"; furigana="けんそん"; arti="rendah hati membumi tidak membanggakan diri"},
    @{kanji="誠実"; furigana="せいじつ"; arti="tulus jujur lurus setia pada komitmen janji"},
    @{kanji="忠実"; furigana="ちゅうじつ"; arti="setia teguh berbakti; akurat menyalin aslinya"},
    @{kanji="忠誠"; furigana="ちゅうせい"; arti="ikrar kesetiaan loyalitas jiwa raga pada negeri"},
    @{kanji="軽薄"; furigana="けいはく"; arti="dangkal sembrono genit tidak berbobot moral"},
    @{kanji="陰険"; furigana="いんけん"; arti="licik culas berhati busuk menusuk dari belakang"},
    @{kanji="邪悪"; furigana="じゃあく"; arti="jahat durjana penuh tipu daya gelap batin"},
    @{kanji="凶悪"; furigana="きょうあく"; arti="keji sadis bengis perbuatan tindak kriminalnya"},
    @{kanji="残忍"; furigana="ざんにん"; arti="kejam tak berbelas kasihan menyiksa mangsa"},
    @{kanji="冷酷"; furigana="れいこく"; arti="berhati dingin kejam membeku tanpa empati kasih"},
    @{kanji="無慈悲"; furigana="むじひ"; arti="tiada ampun tanpa belas kasihan menghabisi lawan"},
    @{kanji="過酷"; furigana="かこく"; arti="sangat berat menekan ekstrem keras ujian tempaan"},
    @{kanji="熾烈"; furigana="しれつ"; arti="sengit berkobar panas rivalitas perebutan tahta"},
    @{kanji="激烈"; furigana="げきれつ"; arti="dahsyat dahsyat menggelegar gempuran serbuan"},
    @{kanji="猛烈"; furigana="もうれつ"; arti="amat dahsyat menghempas kencang badai topan"},
    @{kanji="強烈"; furigana="きょうれつ"; arti="tajam menusuk menyengat kuat impresi bekasnya"},
    @{kanji="鮮烈"; furigana="せんれつ"; arti="amat segar membekas tajam kenangan di benak"},

    # N2 Adverbs, Conjunctions & Modifiers
    @{kanji="かつて"; furigana="かつて"; arti="dahulu kala pernah suatu ketika di masa silam"},
    @{kanji="もはや"; furigana="もはや"; arti="sudah tidak lagi; sekarang sudah terlambat"},
    @{kanji="とうとう"; furigana="とうとう"; arti="akhirnya setelah pergulatan panjang tiba jua"},
    @{kanji="ようやく"; furigana="ようやく"; arti="akhirnya berhasil digapai berkat kerja keras"},
    @{kanji="いずれ"; furigana="いずれ"; arti="kelak suatu saat nanti pada waktunya tersingkap"},
    @{kanji="もしかすると"; furigana="もしかすると"; arti="jangan-jangan ada kemungkinan barangkali saja"},
    @{kanji="もしかしたら"; furigana="もしかしたら"; arti="siapa tahu barangkali terjadi hal demikian"},
    @{kanji="ひょっとすると"; furigana="ひょっとすると"; arti="bisa jadi mungkin secara tak disangka-sangka"},
    @{kanji="まさか"; furigana="まさか"; arti="mana mungkin; sungguh tak dapat dipercaya"},
    @{kanji="断じて"; furigana="だんじて"; arti="sama sekali pantang mutlak tak sudi menyerah"},
    @{kanji="よもや"; furigana="よもや"; arti="sungguh tak disangka; mustahil terpikirkan terjadi"},
    @{kanji="さすが"; furigana="さすが"; arti="memang tak disangsikan kehebatannya; luar biasa"},
    @{kanji="はたして"; furigana="はたして"; arti="apakah gerangan sungguh terbukti tebakannya"},
    @{kanji="現に"; furigana="げんに"; arti="faktanya nyata terbukti di depan mata kepala"},
    @{kanji="いわば"; furigana="いわば"; arti="ibarat kata; laksana perumpamaan kiasan"},
    @{kanji="いわゆる"; furigana="いわゆる"; arti="yang lazim dikenal publik dengan istilah itu"},
    @{kanji="あたかも"; furigana="あたかも"; arti="seakan-akan persis layaknya kenyataan hidup"},
    @{kanji="どうやら"; furigana="どうやら"; arti="tampaknya sepertinya ada gelagat ke arah itu"},
    @{kanji="なにしろ"; furigana="なにしろ"; arti="maklumlah adanya; bagaimanapun keadaannya"},
    @{kanji="なにとぞ"; furigana="なにとぞ"; arti="sudilah kiranya mohon dengan amat sangat"},
    @{kanji="ぜひとも"; furigana="ぜひとも"; arti="sungguh-sungguh sangat memohon kehadiran Anda"},
    @{kanji="なんだか"; furigana="なんだか"; arti="entah mengapa rasa-rasanya ada yang janggal"},
    @{kanji="なんとなく"; furigana="なんとなく"; arti="tanpa tendensi alasan khusus berbisik rasa"},
    @{kanji="なんと"; furigana="なんと"; arti="alangkah betapa menakjubkan kabar sensasionalnya"},
    @{kanji="なんて"; furigana="なんて"; arti="betapa sungguh memesona panorama mahakarya itu"},
    @{kanji="いっそ"; furigana="いっそ"; arti="sekalian saja lebih mantap mengambil keputusan"},
    @{kanji="いかにして"; furigana="いかにして"; arti="dengan cara apa bagaimanakah kiat rahasianya"},
    @{kanji="いかに"; furigana="いかに"; arti="betapa sangat mendalam rasa syukur sanubari"},
    @{kanji="およそ"; furigana="およそ"; arti="kira-kira estimasi secara umum garis besar"},
    @{kanji="おおむね"; furigana="おおむね"; arti="pada umumnya mayoritas besar telah rampung"},
    @{kanji="ほぼ"; furigana="ほぼ"; arti="hampir seluruhnya genap mendekati sempurna"},
    @{kanji="総じて"; furigana="そうじて"; arti="secara menyeluruh garis besar evaluasi umumnya"},
    @{kanji="概して"; furigana="がいして"; arti="umumnya rata-rata kecenderungan perilakunya"},
    @{kanji="ひとえに"; furigana="ひとえに"; arti="semata-mata murni berkat dukungan doa restu"},
    @{kanji="ひたすら"; furigana="ひたすら"; arti="terus-menerus tiada henti tekun berdoa/berkarya"},
    @{kanji="もっぱら"; furigana="もっぱら"; arti="semata-mata khusus berfokus pada ranah itu"},
    @{kanji="もとより"; furigana="もとより"; arti="sudah sejak semula dari awal sudah semestinya"},
    @{kanji="なおさら"; furigana="なおさら"; arti="terlebih-lebih lagi kian bertambah intens"},
    @{kanji="ましてや"; furigana="ましてや"; arti="apalagi lagi orang awam mustahil melampauinya"},
    @{kanji="まして"; furigana="まして"; arti="terlebih-lebih lagi bila kondisi serba terbatas"},
    @{kanji="強いて"; furigana="しいて"; arti="jikalau dipaksakan harus memilih satu opsi"},
    @{kanji="あえて"; furigana="あえて"; arti="memberanikan diri mengambil langkah berisiko tinggi"},
    @{kanji="思い切って"; furigana="おもいきって"; arti="memantapkan tekad bulat melompat maju berani"},
    @{kanji="きっぱり"; furigana="きっぱり"; arti="dengan tegas lugas menolak ajakan dusta"},
    @{kanji="あっさり"; furigana="あっさり"; arti="rasa makanan ringan segar; legawa tanpa dendam"},
    @{kanji="すんなり"; furigana="すんなり"; arti="mulus lancar tanpa hambatan berarti tercapai"},
    @{kanji="みっちり"; furigana="みっちり"; arti="padat intensif digembleng latihan spartan"},
    @{kanji="ぎっしり"; furigana="ぎっしり"; arti="padat berjejal penuh sesak tanpa rongga sela"},

    # N2 Psychology, Mind, Idioms & Yojijukugo
    @{kanji="躊躇"; furigana="ちゅうちょ"; arti="keragu-raguan bimbang melangkah maju"},
    @{kanji="葛藤"; furigana="かっとう"; arti="pergulatan dilema konflik batin manusia"},
    @{kanji="錯覚"; furigana="さっかく"; arti="ilusi optik halusinasi salah sangka penglihatan"},
    @{kanji="妥結"; furigana="だけつ"; arti="tercapainya kesepakatan mufakat kompromi final"},
    @{kanji="融通"; furigana="ゆうずう"; arti="keluwesan fleksibilitas adaptasi dana/sikap"},
    @{kanji="貫禄"; furigana="かんろく"; arti="kharisma aura wibawa kepemimpinan yang matang"},
    @{kanji="貫徹"; furigana="かんてつ"; arti="penuntasan tekad janji hingga titik akhir"},
    @{kanji="執念"; furigana="しゅうねん"; arti="kegigihan tekad membara pantang menyerah"},
    @{kanji="執拗"; furigana="しつよう"; arti="kegigihan ulet mendesak tiada henti"},
    @{kanji="憂慮"; furigana="ゆうりょ"; arti="kekhawatiran mendalam atas krisis masa depan"},
    @{kanji="顧みる"; furigana="かえりみる"; arti="menoleh merenungkan kembali perjalanan masa lampau"},
    @{kanji="省みる"; furigana="かえりみる"; arti="mengintrospeksi menimbang nurani batin diri sendiri"},
    @{kanji="企てる"; furigana="くわだてる"; arti="merencanakan menyusun siasat terobosan proyek"},
    @{kanji="企図"; furigana="きと"; arti="rancangan ikhtiar skenario misi masa depan"},
    @{kanji="目論見"; furigana="もくろみ"; arti="kalkulasi rencana perhitungan strategi tersembunyi"},
    @{kanji="魂胆"; furigana="こんたん"; arti="niat maksud terselubung udang di balik batu"},
    @{kanji="意図"; furigana="いと"; arti="intensi niat maksud tujuan terarah perbuatan"},
    @{kanji="意欲"; furigana="いよく"; arti="antusiasme gairah motivasi tinggi berprestasi"},
    @{kanji="向上心"; furigana="こうじょうしん"; arti="hasrat ambisi positif untuk terus bertumbuh maju"},
    @{kanji="好奇心"; furigana="こうきしん"; arti="keingintahuan penasaran yang membuncah tinggi"},
    @{kanji="探究心"; furigana="たんきゅうしん"; arti="jiwa penjelajah haus riset mencari kebenaran"},
    @{kanji="探求"; furigana="たんきゅう"; arti="penjelajahan pencarian hakikat kebenaran sejati"},
    @{kanji="追求"; furigana="ついきゅう"; arti="pengejaran pemburuan cita-cita mimpi masa depan"},
    @{kanji="追及"; furigana="ついきゅう"; arti="pengusutan tuntas penyelidikan tanggung jawab pelaku"},
    @{kanji="追究"; furigana="ついきゅう"; arti="penelusuran investigasi mendalam hakikat ilmiah"},
    @{kanji="模索"; furigana="もさく"; arti="pencarian jalan keluar terobosan di tengah kebuntuan"},
    @{kanji="試行錯誤"; furigana="しこうさくご"; arti="proses trial and error uji coba berulang kali"},
    @{kanji="紆余曲折"; furigana="うよきょくせつ"; arti="liku-liku lika-liku perjalanan panjang berliku"},
    @{kanji="臨機応変"; furigana="りんきおうへん"; arti="bersikap fleksibel luwes responsif sesuai situasi"},
    @{kanji="切磋琢磨"; furigana="せっさたくま"; arti="saling mengasah dan menggembleng potensi diri"},
    @{kanji="悪戦苦闘"; furigana="あくせんくとう"; arti="perjuangan keras mati-matian melawan kesukaran"},
    @{kanji="一喜一憂"; furigana="いっきいちゆう"; arti="terombang-ambing emosi antara gembira dan cemas"},
    @{kanji="自画自賛"; furigana="じがじさん"; arti="membanggakan memuji karya ciptaan buatan sendiri"},
    @{kanji="十人十色"; furigana="じゅうにんといろ"; arti="setiap insan memiliki keunikan karakter tersendiri"},
    @{kanji="単刀直入"; furigana="たんとうちょくにゅう"; arti="berbicara to the point langsung menusuk ke inti"},
    @{kanji="絶体絶命"; furigana="ぜったいぜつめい"; arti="keadaan terjepit di ujung tanduk tanpa celah lolos"},
    @{kanji="創意工夫"; furigana="そういくふう"; arti="daya kreasi orisinal mencari cara cerdas inovatif"},
    @{kanji="危機一髪"; furigana="ききいっぱつ"; arti="kondisi genting kritis sehelai rambut dari bahaya"}
)

$cleanBatch2 = [System.Collections.Generic.List[object]]::new()
$seenBatch2Kanji = [System.Collections.Generic.HashSet[string]]::new([System.StringComparer]::OrdinalIgnoreCase)

foreach ($c in $candidatePool) {
    $k = $c.kanji.Trim()
    if (-not $existingKanjiSet.Contains($k) -and -not $seenBatch2Kanji.Contains($k)) {
        $cleanBatch2.Add($c)
        $seenBatch2Kanji.Add($k) | Out-Null
    }
}

Write-Host "Filtered clean candidates in candidatePool: $($cleanBatch2.Count)"
